### ISSUE TITLE
Two I catching issues

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#1]
It looks quite good. How ever please consider changing the launcher icon for applications. Or at least make it round edged. Since it cannot be used with short doc having round edges it just does not work with the eye. 

The other thing I noticed is the main "ok" button, the one that is ok for "create folder" or "open". Please change that purple button it just does not make sence there. It does not fit to the theme as other things are orange. No matter how these would be Ubuntu desing concept but after all it is a Gnome not Unity.

**Comment by godlyranchdressing** [comment]
I've fixed the issue with the launcher. If the dash is not in panel mode it'll look like the follow
![preview](https://cloud.githubusercontent.com/assets/27529229/25259920/f460fb66-2616-11e7-8840-13a0ad10dd00.jpg)

The purple stays though, at least in the main branch, sorry.

**Comment by juhaku** [comment]
Thats good. By the picture it looks great as a round button. 

Alright but please consider one thing. If it is and will be only thing in purple color, it will look like a mistake or bug. If you keep purple button I think you should consider adding more things in purple color. Theme should be consistent with its colors.

**Comment by godlyranchdressing** [comment]
Understood. I'm working on putting more purple into the theme so it doesn't look that out of place when it does pop up. It's supposed to serve as contrast, but if it's only there 5% of the time, well... 

It should be easy enough to make a variant with only orange. I know there's no quick install script yet but I'm working on that. I can't make a variant for everyone.
