### ISSUE TITLE
Volume Slider looks odd

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#10]
I'm not sure if this is a bug but if not, it should be. The appearance resembles an upside down guitar pick, which is fine, but mousing over it elongates the bottom slightly and is barely noticeable. Click and holding it changes it to a pill shape, but the whole thing just looks large and unwieldy. I find myself wanting to look behind the thing to see if it's in the right place when I let it go, lol.

The position slider looks great, (albeit a bit large on drag) why not reuse that style for the volume slider? Also, I'm not sure if it goes against your design goals, but have you considered adding some kind of border or shadow or something to distinguish the marker more from the rest? It looks fine without but the result is slightly fuzzy to my eyes.

**Comment by godlyranchdressing** [comment]
Agreed. There's now only one size bump when using the slider and pick. The progress color is a paler orange (as opposed to the same color, whoops) as the picker so it's easier to tell everything apart. I'll keep this open just in case I "fixed" something else than what you're describing though. Will push out the later version with these fixes later today.

**Comment by ElectricGestalt** [comment]
The size bump fix was a big change for the better, but I also meant the odd look on hover. ![Volume Slider](https://u.cubeupload.com/cynicist/guitarpick.png) 

The left side is the normal look, and the right side is what happens when you hover over or click it. I know some indication of a state change is important, but that one is not the most pleasant to look at.

The pale orange was a great solution imo, it looks especially good on the lighter themed apps.

**Comment by godlyranchdressing** [comment]
Woah. That was definitely a mistake and it's been fixed. Lol.
