### ISSUE TITLE
Dash to dock issue

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#100]
Seemingly dash to dock is now having graphical issues. Sharp edges with stripe at top of dash.
![image](https://cloud.githubusercontent.com/assets/26358664/26527878/c280a0c2-43a5-11e7-88ef-6ab5eb11bd66.png)

**Comment by godlyranchdressing** [comment]
Will investigate. It doesn't affect panel mode, it's only there when the dash is at the bottom, and it's hidden if you enable "Force Straight Corner", so I'm thinking it's some built-in dash to dock styling leaking through.
