### ISSUE TITLE
Nautilus tabs using old color

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#101]
The active tabs remain White though you have changed the background to a Gray color. (unless it's intentional, in which case, close this!)

![nautilus tab](http://i.imgur.com/CDhxK7p.png)

**Comment by godlyranchdressing** [comment]
Looks like that was a conscious decision to have the tab blend in with the header buttons in the list view, I hardly use grid view so I didn't notice it. 

I'm starting to notice a lot of background color inconsistencies so I'll work on all of them.
