### ISSUE TITLE
Incorrect color on hover in Rhythmbox

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#104]
Text color changes to orange when it shouldn't. This latest release is really impressive btw. Every time I think the theme is perfect you find a ways to make it better.

![rhythmbox hover](http://i.imgur.com/6GciaQA.png)

**Comment by godlyranchdressing** [comment]
Thanks! Though it really is just inheriting and slightly altering Unity 8's (RIP)/the Suru design language. 

Fixed.
