### ISSUE TITLE
Totem has incorrect color on position nub

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#105]
I'm guessing that light apps are supposed to have the light nub while dark apps have the dark one, but Totem doesn't follow this completely. The volume slider looks correct but the position one doesn't, unlike Gnome MPV. (These new squircle handles look great btw!)

![totem nub](http://i.imgur.com/hBm4Ki8.png)

**Comment by godlyranchdressing** [comment]
Fixed through SASS magic so I wouldn't have to duplicate the lines in the future again.
