### ISSUE TITLE
Textbox border doesn't look cool

### ISSUE THREAD

**Issue by ceyhunnabiyev** [godlyranchdressing/United-GNOME#107]
![screenshot from 2017-06-04 15-40-26](https://cloud.githubusercontent.com/assets/5506156/26761449/bd8f24bc-4940-11e7-8f51-2c9161d4a3ee.png)

**Comment by godlyranchdressing** [comment]
I'll see what I can do. I really wish I could have done like Unity 8 and have focused entries just return a colored cursor but that doesn't seem possible with GTK3. End result just might be the following.

![a](https://cloud.githubusercontent.com/assets/27529229/26762683/4319731c-4914-11e7-8c82-66550f560a21.png)

**Comment by amrsaraya** [comment]
@godlyranchdressing  i think borders are so thick, it would be better if it goes thinner.

**Comment by godlyranchdressing** [comment]
It they were thinner then linked entries (with the dropdown button next to them) would look off.

**Comment by ceyhunnabiyev** [comment]
In previous release, it was great. Why you change this?

**Comment by godlyranchdressing** [comment]
Focused borders are now 2px wide all around.
