### ISSUE TITLE
GNOME-Settings borders

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#108]
These borders for every category really looks ugly. it was better without it

![screenshot from 2017-06-05 07-06-49](https://cloud.githubusercontent.com/assets/21042432/26771323/2c847f22-49c6-11e7-8d36-357f9e16ec67.png)

**Comment by godlyranchdressing** [comment]
Fixed. That was a messup on my part. 

Also, I'd really like if you'd drop the *ugly* and similar embellishments when you open issues. I very much appreciate you making reports but it just comes across as rude. It's also, not surprisingly, discouraging to read.

**Comment by amrsaraya** [comment]
@godlyranchdressing i'm so sorry about that, i really dont mean o be rude but because english is my second language so i hardly talk with it in real life. so my expression and the way i talk never rightly reflect what i mean. 
im so sorry again.

**Comment by godlyranchdressing** [comment]
Oh. It's alright then. If that's the case then I'm being unfair and a little oversensitive. I'll be more understanding. It's cool! :)

**Comment by amrsaraya** [comment]
Thx for understanding :)
