### ISSUE TITLE
Fat borders around windows in overview and logout mode

### ISSUE THREAD

**Issue by Feichtmeier** [godlyranchdressing/United-GNOME#109]
Ubuntu 16.04 with GNOME 3.20 installed from the ubuntu gnome repo

There is a fat border around windows when you logout and when you have the window overview with super key active. If it is the way you designed it then sorry for this "issue" can feel free to delete it xD otherwise I would like to report this "bug" you can see in the screenshots =) thanks for this super awesome theme
![screenshot from 2017-06-05 13-03-48](https://cloud.githubusercontent.com/assets/15329494/26781608/b3eaf3f0-49ef-11e7-82ab-b9b6dd0a5d93.png)
![screenshot from 2017-06-05 13-03-34](https://cloud.githubusercontent.com/assets/15329494/26781609/b3f0a14c-49ef-11e7-952f-ed01ba976ba0.png)

**Comment by godlyranchdressing** [comment]
That's intentional... does it look bad?

**Comment by Feichtmeier** [comment]
Ok then never mind!
Hm "Bad" is too hard. I am not a designer so it could just be a subjective thing. I think it does not fit that well to the rest of the borders. For example the border of a pop up frame when you hover above gnome shell elements. That border is much smaller.

**Comment by ElectricGestalt** [comment]
I disagree. It's nice to have some variation in the theme. I like how the app context menus in the shell and the notification area have the simple "dark/dirty glass" look, while the overview windows and log out dialog have glassy borders too.

It would be boring if everything matched perfectly.

**Comment by ceyhunnabiyev** [comment]
I liked. It looks cool, I think.

**Comment by godlyranchdressing** [comment]
Whoops. Didn't mean to reference this issue in the commit. 

The border on OSD/popup window elements in the Shell theme is just a shoutout to Unity 7's. It's meant to standout and be more noticeable compared to regular borders. I'll work on polishing it so it doesn't look like an accident though. Maybe mimic Unity's faint checkboard pattern.

LightDM + Unity support is on the todo list, but testing is a problem since I'm kind of hesitant to install them Playing around with LightDM and GDM has never ended well for me.

**Comment by Feichtmeier** [comment]
Hey since lightdm is sadly abadonned anyways. A GDM3 theme change works in flat plat and adapta with these thwo commands:

GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
sudo cp -v --backup /usr/share{/themes/$GTK_THEME,}/gnome-shell/gnome-shell-theme.gresource

Could you maybe provide a solution to change the GDM3 theme with these commands too?
Best regards
