### ISSUE TITLE
Nautilus Search Dropdown lacking change on hover

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#11]
The dropdown arrow does not change to orange on hover, and hovering over the 'When' and 'What' categories is not indicated in any way.

Edit: I think you can see the same issue in the Connect to Server area (Other Locations)

**Comment by godlyranchdressing** [comment]
Fixed. Any button that had an image embedded but did _not_ have the class ".image-button" would have behaved the same way. Now there's a catchall rule for _all_ buttons that have images embedded, not just buttons with the class .image-button.
