### ISSUE TITLE
Not rounded button corners

### ISSUE THREAD

**Issue by lepa22** [godlyranchdressing/United-GNOME#110]
![screenshot from 2017-06-05 16-00-43](https://cloud.githubusercontent.com/assets/16370046/26784848/52f46266-4a08-11e7-9326-4f6924416880.png)

As seen in the screenshot, the button corners are not rounded. These buttons are from the gnome-weather app.

**Comment by godlyranchdressing** [comment]
Thanks for the report, it's been fixed. Will be pushing the change later today.
