### ISSUE TITLE
Pixeled background of selected icons in libreoffice

### ISSUE THREAD

**Issue by Feichtmeier** [godlyranchdressing/United-GNOME#111]
Ubuntu 16.04 with GNOME 3.20
LibreOffice 5.3.3.2

The background of selected icons looks very pixeled with the united-gnome theme (see the screenshot)
![screenshot from 2017-06-05 21-50-38](https://cloud.githubusercontent.com/assets/15329494/26800415/81468a14-4a39-11e7-9a26-6eb43079d045.png)

**Comment by godlyranchdressing** [comment]
Fixed. Looks like LibreOffice just doesn't play nicely with rounded buttons. You can grab the update archive off the repo. There's a couple other issues I want to fix before a new release.
