### ISSUE TITLE
Extended border with some applications

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#112]
Hello Aaron, i wish you are fine.
border seems to be invisibly extended which curser allow me to resize apps like ( GNOME-Terminal & Bleachbit ) even when the curser is far from edge "outside the application" unlike Adwaita and other GTK themes.
on the other hand, it works fine with apps like ( Nautilus, GNOME-Software and System Monitor ).
and i couldn't provide a screenshot because cursor doesn't appear in it.

OS : Feodra 25
GNOME-Shell : 3.22.2

Thanks.

**Comment by godlyranchdressing** [comment]
Hey hey.

Looks like the length of a window's shadow is being drawn into GTK2 windows or something like that. Working on it.

**Comment by godlyranchdressing** [comment]
Fixed.
