### ISSUE TITLE
Evolution Mail - Link colour white - United-Opensuse-Darker

### ISSUE THREAD

**Issue by BlueCase** [godlyranchdressing/United-GNOME#113]
OS: OpenSuse Tumbleweed
Evolution: 3.24.2
Theme: United-Opensuse-Darker

Links in mail view are white which is not readable on the gray and white background.
Concerns links in HTML mails and mail addresses in the mail header.
Colour in Edit Window are ok

**Comment by pvoid** [comment]
Same with United Ubuntu theme. Links are white on gray.

**Comment by davidgxxl** [comment]
Same here.

Evolution 3.24.2
Archlinux

**Comment by ElectricGestalt** [comment]
Strangely, this was broken, then worked fine, then became broken again.

**Comment by godlyranchdressing** [comment]
Fixed. Sorry for the wait.

**Comment by davidgxxl** [comment]
Thankyou very much Aaron...

**Comment by BlueCase** [comment]
thanks also from my side.
Tested and work
