### ISSUE TITLE
Dash to dock corners

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#114]
![untitled](https://user-images.githubusercontent.com/21042432/27019869-d209eb34-4f44-11e7-89de-53c59fc37d96.png)

**Comment by godlyranchdressing** [comment]
I think that's been fixed for a while now. Are you using an older version? What's dash to dock's configuration look like?

![a](https://user-images.githubusercontent.com/27529229/27045578-54fcf6ec-4f6f-11e7-8cb4-2dc02f67ac8a.png)

**Comment by amrsaraya** [comment]
I'm using the latest version "commit f01fd80".
this is my configuration
![untitled](https://user-images.githubusercontent.com/21042432/27051820-2dcd7e7e-4fc0-11e7-85b8-dc55c6fc82a4.png)
