### ISSUE TITLE
GNOME-Terminal white line under menu bar

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#115]
Hey Aaron, i wish you are fine.
 I noticed that by chance because my GNOME-terminal's menu bar is always hidden, i thought it worth to be mentioned, but if it was on purpose feel free to close the issue.
Thx alot. 
![untitled](https://user-images.githubusercontent.com/21042432/27021832-9643baf8-4f53-11e7-89e6-8e632326f074.png)

**Comment by godlyranchdressing** [comment]
It's on purpose. All menubars have that border to separate it from the window content.
