### ISSUE TITLE
Default selection in dialog box

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#121]
I reaaaallly liked the way this was before, with the simple dotted box indicating the default option. It's subtle but looks nicer than the jarring bright orange on one side. Why change it? I even remember suggesting it, but the way you went was better.

**Comment by godlyranchdressing** [comment]
I forgot about that. That was way back before the Unity 8 overhaul, so a lot of those changes were written out.

The underline effect won't fit in with the way buttons are styled now so I'll see what I can do.

**Comment by ElectricGestalt** [comment]
Oh no, it was after that. You just removed any indication of it, but that left the dotted box indicator that seems to be a default of Gnome. I would show you a screenshot but it's not possible to take one which shows it.

**Comment by godlyranchdressing** [comment]
Do you mean this?

![doit](https://user-images.githubusercontent.com/27529229/27557573-1cda3cf6-5a88-11e7-9a45-0ce4daffdc6f.png)

**Comment by ElectricGestalt** [comment]
Yeah exactly. I didn't realize the purpose of it before (did not consider indicating the default at all) but now that I do, it seems sufficient and fits the theme well. You think it's not enough on it's own?

**Comment by godlyranchdressing** [comment]
It might be a little hard to see if someone's monitor is some distance away, I think. It'll blend into the button's border. 

I made it the accent color for now. That might change depending on how I and other people feel, though. 
![save](https://user-images.githubusercontent.com/27529229/27809089-adf90284-601a-11e7-9c0e-998d64ca37ea.png)

**Comment by godlyranchdressing** [comment]
Will be sticking with the primary color.
