### ISSUE TITLE
Shell Volume Popup Indicator Bar Color (Ubuntu Variant)

### ISSUE THREAD

**Issue by jsnj** [godlyranchdressing/United-GNOME#122]
Not the panel volume popup indicator bar, but the popup that appears when adjusting the volume with keyboard buttons. The bar indicator color is white on top of a very light gray background making it difficult to see the volume level. Purple would be preferable and consistent with the panel volume indicator bar or just make the light gray background a darker gray.

**Comment by godlyranchdressing** [comment]
Can you post a screenshot? The volume bar and its background look like this in all the variants so I think I might be looking at the wrong thing.
![ac](https://user-images.githubusercontent.com/27529229/27308806-aa6384ac-551e-11e7-96fc-fc22b3d2abcd.png)

![ab](https://user-images.githubusercontent.com/27529229/27308764-6c6902d0-551e-11e7-99f5-c305910d5458.png)

**Comment by jsnj** [comment]
Turns it out it's only on Ubuntu 16.04(GS 3.18.5) which isn't supported. So, apologies. Close this issue. I checked on Ubuntu 17.04 and it shows as your pics indicate. The remainder of the shell looks good on 16.04 though. Wish the GTK was compatible.
