### ISSUE TITLE
Rhythmbox: Volume Symbol has not enough space and there are small lines between each row

### ISSUE THREAD

**Issue by Feichtmeier** [godlyranchdressing/United-GNOME#126]
![screenshot from 2017-07-05 17-58-28](https://user-images.githubusercontent.com/15329494/27873669-37516a6a-61ad-11e7-9cef-ca1e32fd0c0f.png)

The small volume symbol I marked in the screenshot has very little space around it.
Also the small lines between each row could be removed (in my opinion... which can totally be ignored =D)

Best regards and thank you very much!

**Comment by godlyranchdressing** [comment]
Believe me, I've tried. I could very well be doing something wrong, but every column header behaves like it should if you give it a minimum width value or some padding except for that one which gets pushed out of the frame instead.

![a](https://user-images.githubusercontent.com/27529229/27917069-ee69dbf2-6238-11e7-8b27-110bb29a71b9.png)

I'll try to spend some more time on it though.

And the list view lines stay, sorry. Easier differentiation, etc.

**Comment by Feichtmeier** [comment]
![screenshot from 2017-07-10 18-31-23](https://user-images.githubusercontent.com/15329494/28028815-102d2b82-659e-11e7-874c-ba04afa097df.png)

Maybe it is something in the base gtk theme. Which is flat plat in your united gnome and pop gtk/adapta gtk am I right? Just something I have read "somewhere on the internet" and I could be totally wrong.
But in pop gtk that little space for the volume control is existent. They don't have that list view lines though.

**Comment by godlyranchdressing** [comment]
The GTK3 theme is more based on Adwaita since the big Unity 8 switchover. I got it fixed with some padding changes. 

![aa](https://user-images.githubusercontent.com/27529229/28076018-48f312e6-662b-11e7-88cc-ddf79eb7e218.png)

If you're up for removing the list view lines you can add this at the end of the relevant gtk.css file:

    treeview.view {
	  box-shadow: none;
	  border-color: transparent;
	}
