### ISSUE TITLE
Totally broken on Ubuntu 16.04 Gnome gtk3. Help?

### ISSUE THREAD

**Issue by imyxh** [godlyranchdressing/United-GNOME#127]
OK so I have no idea why this is happening, but when I install either the United-Latest.tar.gz or United-Ubuntu-Alt.tar.gz and I install it into the .themes folder, and select it with gnome tweak tool it looks like this: 
![image](https://user-images.githubusercontent.com/12703838/27989937-96bdb562-63fb-11e7-84f8-ee76caefc6b0.png)

As you can see, on/off sliders are totally unusable, and the rest looks nothing like Ubuntu or the screenshots provided. The gnome shell theme works flawlessly, though.
Am I doing something wrong?

**Comment by imyxh** [comment]
Aha. This is broken for gtk3, but looks like it's ok for gtk2.
Screenshot on a-widget-factory:
![image](https://user-images.githubusercontent.com/12703838/27989926-50c6e182-63fb-11e7-85da-6947df56a604.png)

**Comment by godlyranchdressing** [comment]
16.04 uses GNOME 3.18. The GTK3 theme would only work for 3.20 and up, since some CSS node stuff was changed for standardization reasons (IIRC). You'll either have to upgrade to 3.24 by adding the appropriate PPAs or switching over to 16.10 or 17.04. Sorry about that.

**Comment by imyxh** [comment]
@godlyranchdressing Ah, I see. I thought it was my problem. :)
