### ISSUE TITLE
Polari visual glitch

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#128]
Not sure what's going on here.

[Polari bug](http://i.imgur.com/YHQH4xP.png)

Also, this part doesn't look great on mouseover.

[Polari bug two](http://i.imgur.com/HNfDuHt.png)

**Comment by godlyranchdressing** [comment]
Looks like Polari's headerbar is split into two so the window rounding is being applied to both. Should be a simple fix for both. I'll push it in a bit.

**Comment by ElectricGestalt** [comment]
The headerbar is fixed and looks much better, thank you. Is it possible to change the text color of the username to White on hover?

**Comment by godlyranchdressing** [comment]
Forgot to do that, actually. Done.

**Comment by ElectricGestalt** [comment]
The text color change on hover isn't working with the latest release.

**Comment by godlyranchdressing** [comment]
<sub>I forgot again.</sub>
Fixed for real this time. That button shouldn't have been changing on hover, it behaves like how it should now.
