### ISSUE TITLE
Copr repo for Fedora users

### ISSUE THREAD

**Issue by IamPr377y** [godlyranchdressing/United-GNOME#13]
I have created [copr repo](https://copr.fedorainfracloud.org/coprs/vldslv/united/) for this theme and will try to keep it up to date. Build process relies on `United-Latest.tar.gz` file, so if @godlyranchdressing changes anything, it will fail.

Right now we can install package by running these commands
```bash
$ dnf copr enable vldslv/united
$ dnf install united-theme
```

**Comment by godlyranchdressing** [comment]
That's fantastic. Don't worry, that file is there precisely for install scripts and so on.

**Comment by IamPr377y** [comment]
@godlyranchdressing It would be nice if you added link to this repo to installation section in readme. If only you don't mind third party repos, of course. Build script is located [here](https://github.com/IamPr377y/copr/blob/master/united/copr.sh), just letting you know I don't do anything suspicious.
