### ISSUE TITLE
Button consistency issue

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#130]
With some buttons (appears to be the ones with a dropdown menu), the text simply changes to orange on hover. On others, it applies a rounded rectangle border in addition to the text color change. All buttons should probably have the same background border, which looks quite nice and distinguishes the buttons better.  Illustrated below.

![button bug1](http://i.imgur.com/APajga4.png)

![button bug2](http://i.imgur.com/Z7uOFxu.png)

**Comment by godlyranchdressing** [comment]
I know Evolution has that problem. Are there any other apps? I agree though, I'll work on fixing it. I picked up a couple things with Aduru that I plan to bring over to this theme. 

I pushed a couple fixes that mostly target Evolution but should also (hopefully) apply to any other toolbars that have a similar problem.

**Comment by ElectricGestalt** [comment]
Honestly, I haven't seen any other apps that use it.

These fixes have some issues. The border has now disappeared from regular buttons like those in Transmission, while the buttons in Evolution have a different border than the previous one, and no orange text.

In addition, for some reason, the icons of some of those buttons in evolution have also changed to a Black & White variant over the regular colored ones.

**Comment by godlyranchdressing** [comment]
Fixed Transmission's issue, I went about the wrong way trying to avoid affecting Rhythmbox's toolbar. Toolbar buttons will now just have a simple border on hover instead of the 3D border.

As for Evolution, that was me switching over to symbolic icons to avoid the huge icons in Evolution's mail view. Decided to just change some margins around instead of getting rid of the familiar icons.

**Comment by ElectricGestalt** [comment]
Very close, but you took away the orange text on hover. ><

**Comment by godlyranchdressing** [comment]
I left it purple on purpose. That's the color Polari asks for, and I'm not too fond of purple text that becomes orange when hovered on.

**Comment by ElectricGestalt** [comment]
Think you meant to comment on the other bug? Here I'm saying you took away the orange highlight on hover that was there before on all buttons.

In the Polari bug, what happens is you have purple text on a white background, which looks fine, that then becomes purple text on a dark orange background on hover, which is hard to see and not attractive. There, I was suggesting that the purple text change to white on hover, meaning that the end result is white text on an orange background.

**Comment by godlyranchdressing** [comment]
Ohh. I don't know what's wrong with me lately, I even forgot to reply to this comment. Sorry! The button now behaves like a special button (orange background on hover + white text).
![andidoublecheckedthistime](https://user-images.githubusercontent.com/27529229/28400698-e12605ba-6ce2-11e7-935e-7709f052edcc.png)

**Comment by ElectricGestalt** [comment]
That looks much better, thanks! One last thing and I'll leave you alone for a while lol. The evolution buttons look great, exactly how they should to match the rest of the theme, except you forgot to change the text to orange on hover.

**Comment by godlyranchdressing** [comment]
Done. Had a bit of a goof in mimicking the effect for the GTK2 theme.
