### ISSUE TITLE
GNOME-Control-Center & GNOME-Help " Upper Left Corner "

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#131]
The upper left corner isn't rounded.

![untitled](https://user-images.githubusercontent.com/21042432/28091680-7b2abf84-6699-11e7-90d7-eefdbc12065a.png)

![untitled1](https://user-images.githubusercontent.com/21042432/28091630-4691af30-6699-11e7-833b-1bb03e20c2e6.png)

**Comment by godlyranchdressing** [comment]
Fixed. Brought about after #128. Will push the fix in a bit
