### ISSUE TITLE
[Fedora 26] Color issues in Shell

### ISSUE THREAD

**Issue by 1Claude** [godlyranchdressing/United-GNOME#134]
Hi, 

First of all, thanks for your great work ! Really beautiful.

In Fedora 26, I noticed some issues in GTK Theme United-Fedora Darker & in United-Fedora Shell Theme.

![capture du 2017-07-14 13-17-35](https://user-images.githubusercontent.com/19640810/28222813-00fa0846-6897-11e7-96aa-a90df5ca4ab8.png)

Maybe the buttons should be blue instead of green ?

Now the rest are some color issues in United-Fedora shell theme. In the sound and screen light button color is yellowish. Should be blue ? No problem with the calendar showing blue.

![capture du 2017-07-14 13-12-58](https://user-images.githubusercontent.com/19640810/28223165-55d61700-6898-11e7-88e4-4e263dbbc149.png)
![capture du 2017-07-14 13-13-47](https://user-images.githubusercontent.com/19640810/28223163-55d35a1a-6898-11e7-8aa7-e428bcc5b80d.png)
![capture du 2017-07-14 13-14-04](https://user-images.githubusercontent.com/19640810/28223164-55d5f702-6898-11e7-841d-7a831d264650.png)

**Comment by godlyranchdressing** [comment]
No problem. I might have slowed down a bit but this is still just fun for me. 

A lot of people point out those colors but contextual colors like that are a Unity 8/Suru thing. The gold is actually taken from [Fedora's color palette](https://fedoraproject.org/wiki/Logo/UsageGuidelines). 

I just pushed a hacking.md file that should help out anyone that wants to change some colors around but those colors are staying as is, sorry.
