### ISSUE TITLE
LibreOffice : white square at the top right

### ISSUE THREAD

**Issue by 1Claude** [godlyranchdressing/United-GNOME#135]
LibreOffice, notice the white square on the right, in United-Darker theme. Maybe you could take a look at what Adapta and Arc have done to manage that.

![lo](https://user-images.githubusercontent.com/19640810/28237364-7b6ed1e6-690b-11e7-9b82-43c6d1929d7a.png)

**Comment by godlyranchdressing** [comment]
Seems to be a common thing among themes with dark headerbars. LibreOffice doesn't use any ids or classes so I wrote a very specific rule that hopefully only fixes this issue in LibreOffice. I just pushed the updated theme, but if that fix ends up affecting any other programs then the button might need to be left as is.

**Comment by 1Claude** [comment]
Thanks a lot !!

Works perfectly with LibreOffice. 

If I ever see some bug from the change, I'll let you know. Pretty sure all will be good. 

You might want to do the same with your other themes.

**Comment by 1Claude** [comment]
For the fun of it, here's the result of my "future nostalgia" desktop with your beautiful theme.  
![ubuntugnome](https://user-images.githubusercontent.com/19640810/28249566-36eb69fa-6a26-11e7-982b-fbd01f98fb4f.png)
