### ISSUE TITLE
Shutdown Dialog focus issue

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#136]
Shutdown Dialog doesn't be focused on when opened from the menu .. i have to click any keyboard button or one mouse click to get it focused.
so, it takes 2 clicks by keyboard or mouse to select shutdown or other option.
NOTICE: it works fine with ALT+CTRL+DEL
Theme: United-Fedora-Compact

![untitled](https://user-images.githubusercontent.com/21042432/28243371-9d0d2ac2-69cf-11e7-8f5a-60ca971f223d.png)

**Comment by amrsaraya** [comment]
It seems to be a gnome-shell issue because it affects all themes not UNITED-GNOME only
GNOME-SHELL : 3.24.2

**Comment by godlyranchdressing** [comment]
Yep. That seems to be a GNOME-Shell bug. I think @juhaku pointed it out at one point but he runs Ubuntu. Are you running Fedora 26?

**Comment by ceyhunnabiyev** [comment]
Same problem on me. Manjaro  Gnome (3.24.2) edition

**Comment by amrsaraya** [comment]
@godlyranchdressing Yup. I'm running Fedora 26

**Comment by ceyhunnabiyev** [comment]
Hi @amrsaraya , @godlyranchdressing  ,
This's been fixed in gnome-shell version 3.24.3: 
https://github.com/GNOME/gnome-shell/commit/ecea0218f2d32841c32cd94dc586b78a99bfd60d

**Comment by amrsaraya** [comment]
@ceyhunnabiyev good news :D
