### ISSUE TITLE
Checkmarks in menus don't show unless hovered, at least in Libreoffice

### ISSUE THREAD

**Issue by imyxh** [godlyranchdressing/United-GNOME#138]
Here's a gif:
![peek 2017-07-19 17-44](https://user-images.githubusercontent.com/12703838/28399903-ca594e32-6cc4-11e7-8632-8b92cee4a725.gif)
As you can see, the checkmarks are empty (even when they're supposed to be checked) but slightly darker than the boxes that aren't checked.
I think it's just me?
Running 3.20 on Ubuntu 16.04.

**Comment by godlyranchdressing** [comment]
That should be fixed in the pre-release versions on the repo. Funnily enough, I worked on the check and radio buttons just yesterday. That looks like an older version of LibreOffice (since it seems to be using straight GTK2) but I'm assuming the finetuning I did should still apply.

**Comment by imyxh** [comment]
Aha, didn't even need to download the pre-release as installing the libreoffice-gtk3 package updated it to gtk3 and now it's working. Thanks.
