### ISSUE TITLE
Login theme install script returns "Failed to locate 'assets/calendar-arrow-today.svg' in current directory."

### ISSUE THREAD

**Issue by imyxh** [godlyranchdressing/United-GNOME#139]
```
~$ ./.themes/etc/login-gnome-shell/united-login-theme-installer.sh -i ubuntu
Installing...
Installing ubuntu login theme...
Uninstalling current theme and restoring previous theme...
Asking sudo rights to restore.
Completed!
Asking sudo rights to move original theme as back up.
mv /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.bak
Checking does ubuntu folder exist in current directory.
Find compile command
Compile command found: /usr/bin/glib-compile-resources...
Compiling gnome-shell-theme.gresource.xml...
gnome-shell-theme.gresource.xml: Failed to locate 'assets/calendar-arrow-today.svg' in current directory.
Failure in execution! Exiting with code: 1
~$ 
```
It seems that no matter where I run this from, this error appears.

**Comment by ceyhunnabiyev** [comment]
@imyxh , You have to run this as superuser.

**Comment by imyxh** [comment]
No, same result with superuser and root. And it asked me for my sudo password to move the original theme anyway.

**Comment by ceyhunnabiyev** [comment]
@imyxh , I understood, find calendar-arrow-today.svg from original theme, copy this to assets folder in your current directory

**Comment by imyxh** [comment]
I can't even find the assets folder of the original theme. It's not located in /usr/share/gnome-shell.
Anyway, I think this is a bug in [gnome-shell-theme.gresource.xml](https://github.com/godlyranchdressing/United-GNOME/blob/master/extras/login-gnome-shell/ubuntu/gnome-shell-theme.gresource.xml) as it lists `calendar-arrow-today.svg` on line 10, which doesn't exist in the assets folder, but `calendar-today.svg` does, and isn't listed.
And just to confirm, the [original gnome shell theme](https://github.com/GNOME/gnome-shell/blob/master/data/gnome-shell-theme.gresource.xml) doesn't have an asset called `calendar-arrow-today`.

**Comment by imyxh** [comment]
Yep, exactly what I suspected. Renaming `calendar-arrow-today` to `calendar-today` in the xml file fixes it.

**Comment by godlyranchdressing** [comment]
Yep. That's a typo. Sorry about that, looks like we fixed it at the same time.
