### ISSUE TITLE
Odd purple color probably in wrong place & no underlining anymore?

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#14]
Hello,

I think in below image there is purple color probably little wrong place. The purple is in file explorer's search popover. Also how about having orange highlight color for scrollbars when pressing them?
![image](https://cloud.githubusercontent.com/assets/26358664/25315781/8cbad488-2863-11e7-9e08-b62ffb944d48.png)

Another thing do I remember wrong that there used to be underlining hover on file explorer. But at least now there is no such.
![image](https://cloud.githubusercontent.com/assets/26358664/25315812/edea1674-2863-11e7-863e-7ed204ea5a59.png)

**Comment by godlyranchdressing** [comment]
They're both inheriting rules from other things I changed. I'll get on that. Fix one thing, break something else, etc. They haven't been fixed yet despite the last commit.

**Comment by godlyranchdressing** [comment]
Fixed.

**Comment by juhaku** [comment]
Great, keep it up. Yea that's usual fix something break something else.
