### ISSUE TITLE
Titlebar and Panel are merged in the Dark version

### ISSUE THREAD

**Issue by DraganKovacevic** [godlyranchdressing/United-GNOME#147]
When using a dark version of the theme, if window is maximized there is no clear separation of Titlebar and Panel, as there is in the light version of the theme.

![screenshot from 2017-08-06 19-22-59](https://user-images.githubusercontent.com/7206237/29005506-ff97f956-7adc-11e7-919f-5081ec6db273.png)

![screenshot from 2017-08-06 19-21-33](https://user-images.githubusercontent.com/7206237/29005507-ff9a1bc8-7adc-11e7-96c3-fe64dfc25c63.png)

**Comment by godlyranchdressing** [comment]
That's intentional. The idea was that if an extension merges the titlebar with the top bar (like Unity 7) then it would look seamless. The shadow only exists in the light shell theme to avoid the top bar looking too flat when no windows are open.
