### ISSUE TITLE
Text boxes & dialogs

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#15]
Hi,

Below is an example of app menu's search box. Should it have some extra styling as it now is regular white box. The same will be with the login screen's text box if the .css file is being used as login screen's theme.
![image](https://cloud.githubusercontent.com/assets/26358664/25317851/f9264fe6-2889-11e7-862c-5298270c2e5f.png)

Also for the shutdown computer dialog or any other similar dialog. The screen need to be focused before pressing the buttons. That means that there is a need to perform 2 clicks for the action. First click will focus the screen, second one will execute performed action. It does not matter where the first click is performed it seems that it only needs activate the screen before pressing buttons for the dialog.

Please check these out. 

And you are doing great work here.

**Comment by godlyranchdressing** [comment]
Fixed. Colour is now added when the overview search box is focused on. I fixed the issue with the dropdown arrow [see here](https://github.com/godlyranchdressing/United-GNOME/issues/11). 

I'm not understanding the dialog issue though. That sounds more like a focus problem than a theme problem. 

Also, thanks!

**Comment by juhaku** [comment]
Great,

Alright, I need to test it with other theme then as well. It might be ubuntu gnome 17.04 fault.

**Comment by godlyranchdressing** [comment]
Alright. I just uploaded the latest version with some of the issues fixed. I know it's a Ubuntu theme and all I'm making but 17.04 has been a bit buggy for me.

**Comment by ElectricGestalt** [comment]
> Also for the shutdown computer dialog or any other similar dialog. The screen need to be focused before pressing the buttons. That means that there is a need to perform 2 clicks for the action.

Not a theme bug apparently. It occurs with Adwaita as well.

**Comment by juhaku** [comment]
Allright, thanks a lot guys so I do not need to worry about it.

**Comment by godlyranchdressing** [comment]
Confirmed to be a Shell bug.
