### ISSUE TITLE
Request for gray text in Dark and Darker Compact versions

### ISSUE THREAD

**Issue by davidgxxl** [godlyranchdressing/United-GNOME#153]
This is no a bug but a request for a litle improvement for changing the absolute white text color(#ffffff) for a gray scale text(maybe #DCDCDC) over black colors in top panel, titlebars and menu bar at least.

I did made some changes to adjust this in my own configuration, but I dont know apply this for all elements, just for title bar in gnome3 apps and gtk2 menus, no more. :(

The reason for this is because the white text over black color become eyes stress after some hours or in some lighting conditions.

I can help testing this changes if you consider commit it.

Thanks.

**Comment by davidgxxl** [comment]
Hi Aaron. Thanks for include this request in this awsome theme.

In my particular case, I had noted that the background color become a bit dificult to focus the icons, fonts and other elements over it.

I just did a few changes to adjust the background color for shell top panel, gtk3 titlebar, gtk2 titlebar, menus.

The chage that I did was #111111 to #333333 which is the official "Cool grey" from ubuntu palette colours. http://design.ubuntu.com/brand/colour-palette

I think this tones of background colors are better if we stay long time in front of the screen. e.g. Pop theme dark color and ambiance dark color.

Here some screenshots of my own tweaks.

![sublime](https://user-images.githubusercontent.com/9441096/30257802-95ab846a-9682-11e7-85e8-4e1e312310e3.png)

![nautilus](https://user-images.githubusercontent.com/9441096/30257814-a449381e-9682-11e7-9dd4-1e89e897f5ad.png)

![libreoffice_writer](https://user-images.githubusercontent.com/9441096/30257810-9d694034-9682-11e7-89ba-8dc9607268c1.png)

I'm sure you can do a better job creating an "Ambiance" version if you want. I'll be glad if you think about it and eventually you do it.

If you think that my tweaks can help you to create that, please let me know.

Again thanks for this amazing theme.

Cheers.

**Comment by godlyranchdressing** [comment]
No problem. 

And that looks really nice! An Ambiance variant is a great idea. I'll make one in a couple of days when I have the time. I've been really busy lately and haven't been able to work on the theme as much as I'd like.

In a couple screenshots of Unity 8 there's a dark theme that uses #242429 as its background color if you want another dark color that's easier on the eyes.

**Comment by davidgxxl** [comment]
That'll be really nice.

My enviroment is gnome 3.24 in Archlinux in fact. And your theme works very well.

I'm using the compact version of the theme.

Even vscode's sidebar color is #333333. I didn't know that.

Here another screenshot of vscode.

![vscode](https://user-images.githubusercontent.com/9441096/30354603-7af1c8d0-97fb-11e7-8a8a-f35c54006178.png)
