### ISSUE TITLE
Ubuntu 17.10 menu bar has a gradient when maximized

### ISSUE THREAD

**Issue by Feichtmeier** [godlyranchdressing/United-GNOME#155]
Hi, I am on 17.10 and the menu bar has a gradient like this with maximized windows:

![bildschirmfoto von 2017-09-12 20-33-37](https://user-images.githubusercontent.com/15329494/30342301-b2f1bb8e-97f9-11e7-8fb8-8e410899e7c2.png)

I guess this has something to do with the new GNOME transparent menu bar they implemented in one of the last versions since 3.24

**Comment by godlyranchdressing** [comment]
Does that happen with other themes as well? And are you using the opaque shell theme or the transparent one? That actually looks like the same gradient effect Ubuntu uses for the Ambiance Shell theme. I'll install 17.10 and do some testing.

**Comment by Feichtmeier** [comment]
@godlyranchdressing It does not appear with adwaita, ambiance and pop-gtk. Those three have a solid top bar when you maximize the window/attach it to the launcher/top bar.

I think that the reason for this could be the transparent top bar setting the implented in the last gnome update. They may disable it soon: https://bugzilla.gnome.org/show_bug.cgi?id=787446

**Comment by Michael-A-D** [comment]
The same problem also exists with other user themes: arc-grey-dark for instance. After some tweaking on ubuntu-gnome, I can confirm that it's clearly related to the transparent top bar. My guess is that ubuntu display this gradient bar when a window is maximized, overriding the theme.

**Comment by 1LinuxGuy** [comment]
If you want to tweak Ubuntu, you better install gnome-session and customize from there.

**Comment by kfstudio** [comment]
In gnome-sell.css you can add "background-gradient-direction: none;" : 
/* TOP BAR */
#panel {
  background-color: #111111;
  box-shadow: none;
  font-size: 9.5pt;
  height: 2em;
  **background-gradient-direction: none;**
}
It resolve this issue for me.
