### ISSUE TITLE
The top panel after the last manjaro update began to look like this

### ISSUE THREAD

**Issue by darleneeon** [godlyranchdressing/United-GNOME#158]
![issue](https://user-images.githubusercontent.com/29887971/31050990-9b5b31ee-a686-11e7-9434-d09ef1ddc59f.png)
![issue2](https://user-images.githubusercontent.com/29887971/31051008-44d3f80a-a687-11e7-8136-3a40abac9185.png)

**Comment by godlyranchdressing** [comment]
Can you see if [this](https://github.com/godlyranchdressing/United-GNOME/blob/master/United-Arch.tar.gz
) fixes the issue?

It looks like some type of inheritance problem, but I'm not getting that under 3.24.3 on Fedora.

**Comment by darleneeon** [comment]
@godlyranchdressing it was manjaro issue. already fixed.
