### ISSUE TITLE
GTK2.0 scrollbars

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#16]
Hi,

The scrollbars with the orange color looks great with gtk3.0, however with gtk2.0 apps the scrollbars are still with the grey color. Even pressing the highlight is the darker grey. 
![image](https://cloud.githubusercontent.com/assets/26358664/25342510/ec714a90-2914-11e7-95e7-7492cfd81b4e.png)

Thanks

**Comment by godlyranchdressing** [comment]
Semi-fixed. The asset source for gtk-2.0 seems to use an embedded image for the scrollbars as opposed to an object so the colour can't easily be changed. They'll need to be remade from scratch so this'll stay open till then. A not-perfect replica to the original is being used for now.

**Comment by godlyranchdressing** [comment]
In-progress.
