### ISSUE TITLE
Desktop icon text color isn't white

### ISSUE THREAD

**Issue by h4ndshake** [godlyranchdressing/United-GNOME#160]
The desktop text color isn't white as stated in commit 0dac8eb4a5131936bf5b92d59c85a5a5532d1d22

The selector value (.nautilus-desktop.view ) is now white, but the text on desktop hasn't changed accordingly... maybe this color resides in another selector?

EDIT: I've tested with other variants, and reboot my machine.

![captura de tela de 2017-10-09 03-14-19](https://user-images.githubusercontent.com/12601769/31326699-fb10e6fa-ac9f-11e7-8793-ac2ba6554e84.png)

**Comment by godlyranchdressing** [comment]
Stupid mistake on my part. I forgot to add a dot, it should work now.
