### ISSUE TITLE
Default launcher button with default highlight behavior

### ISSUE THREAD

**Issue by rpgdev** [godlyranchdressing/United-GNOME#168]
Can you make a version with default activities button with default highlight behavior? I know the default launcher icon is on launcher-icons.tar.gz but I haven't been able to set it up with the current release by replacing the launcher icon on the ubuntu variant.

**Comment by godlyranchdressing** [comment]
I just tested it. You're right, it wasn't changing until I restarted the Shell session. I had to log out and log back in under Wayland, but I'm assuming the Alt + F2 and r command should do the trick under X as well.

**Comment by rpgdev** [comment]
Good to know. Can you make an official "default logo" version though?

**Comment by godlyranchdressing** [comment]
Maybe in the future when I tidy things up and settle on a proper way to handle things, since I'm planning on scraping this and basing it entirely on Adwaita. For now it's a single file replacement.
