### ISSUE TITLE
Login theme

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#17]
Hello,

I thought that I could contribute a little more so I made login theme for you. I upload it very next post. 
If you want I can make more of them. This is based on the "United". Not light, not dark, nor mixed ones.

Login theme need to placed to the folder /usr/share/gnome-shell/.

This login theme is made for Ubuntu GNOME.

**Comment by juhaku** [comment]
Here is the screenshow how it looks:

![united_login_screen](https://cloud.githubusercontent.com/assets/26358664/25346452/48216f54-2920-11e7-88f7-e0419b33d121.png)

Below is the resource file that need be placed to above mentioned folder in order it to take effect.
[gnome-shell-theme.zip](https://github.com/godlyranchdressing/United-GNOME/files/952372/gnome-shell-theme.zip)

Instructions:
- Extract file
- Place it to above mentioned folder
- Press alt + f2 then type r (will reload gnome shell) This will make the changes available for the lock screen.

Note only after reboot changes will be available in login screen!

**Comment by godlyranchdressing** [comment]
Wow, looks fantastic! A couple inconsistencies though. For the light variant: the background for text entry fields should be #F4F4F4 with the text color being #505050. The button's text remains dark even if it's focused on. Also see below for button focus. The shadow would be irregular. 

![screen1](https://cloud.githubusercontent.com/assets/27529229/25363381/0959b580-2928-11e7-86ef-9792d0220a6c.jpg)
![screen2](https://cloud.githubusercontent.com/assets/27529229/25363382/09708404-2928-11e7-876d-9841640af91b.jpg)

I don't know if any of this is possible since I've never tweaked GNOME like this before but thanks for doing this. It makes everything feel more official. If you can fix those issues I'll gladly merge this into the repo or whatever the proper term is.

**Comment by juhaku** [comment]
Glad to hear. I'll look into these issues and do what I can. I'll provide #F4F4F4 colored with and without transparency just in case. I thought that the transparence In the login password field would be cool instead of the just blank white box. I'll get back with the result. Also I'll try to change one more picture as well if I can. But that has been tricky since I cannot see where it is coming from. The picture Im trying to change is screensaver picture on login screen.

**Comment by godlyranchdressing** [comment]
I just noticed that it seems to affect some base resources that all themes pull from. I was working on Minwaita and wondering why there was random orange all over the place. Lol. There was also a black border around a couple shell menus. 

We'll have to either put up a disclaimer or you'll have to decide if to make it a lighter mod so that people could still switch around their shell theme.

**Comment by juhaku** [comment]
Haha. That's something. Indeed it might affect on global resources as there are certain folders gnome will read the themes. And I guess all the theme resources for certain theme are packed together for gnome to use somehow. Anyway I'm not exactly sure how it works but multiple locations are used for same theme.

Yea there is a catch to use login theme. As it is made from United's gnome-shell.css so it makes some United's css styles as public. If some other theme would be used as foundation for the login theme instance Adwaita it would be bigger process to change required css to get it actually look like the css you have already made.  

Quicker at least for now is to put up disclaimer that this login theme should only be used with United Shell theme. And that people always will take backup of the original adwaita login theme. 

Probably this could be done above the Adwaita so only small peices would be changed for the login theme. How ever if people would use any other shell theme in same way they might wonder why some things look like Adwaita or little odd. As it is still global theme location. 

I can also investigate whether there is actually a place where only login phace is reading the theme.

If you need the origial Adwaita login theme I can also provide it here. I should have a back up.

**Comment by juhaku** [comment]
Here is the one with transparency, modified the text and background colors and buttons.
I'm afraid that this is quite much best can be done for this. Since login does not support css3 :(.

![purple_login](https://cloud.githubusercontent.com/assets/26358664/25396765/7b210508-29ee-11e7-9bb6-9897ceeafbc1.png)
[gnome-shell-theme.zip](https://github.com/godlyranchdressing/United-GNOME/files/955796/gnome-shell-theme.zip)

**Comment by juhaku** [comment]
Here is the solid colored one.
![purple_login_solid](https://cloud.githubusercontent.com/assets/26358664/25397469/0b3813aa-29f1-11e7-8776-243797dac280.png)
[gnome-shell-theme.zip](https://github.com/godlyranchdressing/United-GNOME/files/955849/gnome-shell-theme.zip)

**Comment by juhaku** [comment]
As a side note, my mouse is over close button in both of pictures so it is hovered. I put the default hover look what is used in allover to the buttons.

If dark themed login screen is also wanted I can make it, just give me color's that should be used.

Hope these are worth something, even though it currently using them affects to global gnome shell.

**Comment by godlyranchdressing** [comment]
Looks great. I'll include it with a disclaimer, that's all. I think most of these "system" mods do that. Do you want to push it to the repo?

**Comment by juhaku** [comment]
Yea, I could push it to the repo to another brach so you could merge it from it and then edit the folder structure as you wish. I will push sources and one readme how to compile it. and of course compiled versions inside the sources as well.

**Comment by godlyranchdressing** [comment]
I sent you an invite. I actually didn't know I had to invite people.

**Comment by juhaku** [comment]
Great thanks I will accept it and then push the changes.

**Comment by juhaku** [comment]
I pushed to the repo to a new branch called feature_login_themes. You can merge things from there. Also if there is anything unclear please don't hesitate to ask.

**Comment by godlyranchdressing** [comment]
Done! It's been merged.
