### ISSUE TITLE
Hover Effect on Menus

### ISSUE THREAD

**Issue by sharifzadesina** [godlyranchdressing/United-GNOME#171]
Hi
Please open file manager and hover on active breadcrumb item, this will happen:
![screenshot from 2017-12-10 20-32-48](https://user-images.githubusercontent.com/15300551/33807279-6e9909de-dde9-11e7-8920-e5818ab97b11.png)

**Comment by godlyranchdressing** [comment]
Just pushed a fix.

**Comment by sharifzadesina** [comment]
@godlyranchdressing dude I've downloaded last from master gain but it is not fixed.

**Comment by godlyranchdressing** [comment]
@sharifzadesina Don't worry about it. Nautilus usually just needs to be properly closed (I just type "killall nautilus" in a terminal)
