### ISSUE TITLE
Unfocused window greyed out

### ISSUE THREAD

**Issue by g00nix** [godlyranchdressing/United-GNOME#176]
I am aware this is by design, but it's really annoying when you have 3 monitors and multiple windows opened. The text on the entire window gets grayed out. I tried to go through the css and find the code where this is done, but didn't manage to find it. 

Can somebody please point me to the css line of code which dictate the FG color of text on unfocused windows?

**Comment by izznogooood** [comment]
same issue.

**Comment by gun1x** [comment]
@izznogooood I changed to OSX-Arc theme for multiple monitors. 

But I would still like to see this theme fixed, because it is really nice.

**Comment by davidgxxl** [comment]
I had tried modify some colors in gtk3>gtk.css whitout success. I had modified the color for shell top panel and apps title bar with the new ubuntu theme color. I use and follow this great theme from a year ago or so. 

It will be nice see this "bug" solved soon.

Thanks again Aaron for this great theme...


P.S. This is how "my" custom theme looks like. And you can see the bug in the rigth window :(

![pantalla_completa_bug_theme](https://user-images.githubusercontent.com/9441096/36957614-ea778152-200b-11e8-8bb7-df3531ec51e4.png)

**Comment by izznogooood** [comment]
Arc which is one of its base code dims the frame/header, not the content.

**Comment by davidgxxl** [comment]
izznogooood, Yes, and not only that... In a previous version(a version from about 6 or 8 months ago) this same theme dims the frame/header like Arc

**Comment by agoncalo** [comment]
Same here. Cannot read unfocused windows properly.

**Comment by maxiqboy** [comment]
please fix this,
