### ISSUE TITLE
GTK warnings when United Dark theme is used under Gnome (Gtk 3.22)

### ISSUE THREAD

**Issue by wangxa** [godlyranchdressing/United-GNOME#2]
There are several GTK warnings will be shown under the United Dark theme, if you launch a command like gtk3-widget-factory or gvim:

`(gtk3-widget-factory:5368): Gtk-WARNING **: Theme parsing error: gtk.css:1123:15: unknown value for property`

`(gtk3-widget-factory:5368): Gtk-WARNING **: Theme parsing error: gtk.css:3507:62: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

`(gtk3-widget-factory:5368): Gtk-WARNING **: Theme parsing error: gtk.css:3511:80: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

`(gtk3-widget-factory:5368): Gtk-WARNING **: Theme parsing error: gtk.css:3547:68: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

`(gtk3-widget-factory:5368): Gtk-WARNING **: Theme parsing error: gtk.css:3552:80: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

The first warning is caused by the wrong value of `font-weight` property. In GTK CSS specification, the font weight is defined as:
          **100 | 200 | 300 | normal | 400 | 500 | 600 | bold | 700 | 800 | 900**
      **where, normal = 400, bold = 700**
But your value is 'light', and there is no such defintion.

For the other warnings, just replace `:insensitive` with `:disabled`.

Thank you.

**Comment by godlyranchdressing** [comment]
I'll make the appropriate changes, thanks.
