### ISSUE TITLE
Epiphany colors incorrect

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#21]
Most of the items on this menu look fine but two are definitely off. In this screenshot, I'm not hovering over any menu items and yet the decrease size item has a gray background. (this also occurs in gedit) It appears like the percentage item is also broken.

![Epiphany menu](http://u.cubeupload.com/cynicist/epiphany.png)

**Comment by godlyranchdressing** [comment]
Fixed for now. Though this ties back to the increasingly large issue of the purple text-buttons not being a good ancestor for other button types. I didn't want to go vanilla for the default buttons, but I'll probably have to.
