### ISSUE TITLE
Create Releases

### ISSUE THREAD

**Issue by ainola** [godlyranchdressing/United-GNOME#22]
This and Minwaita are fabulously made. Thanks for your great work!

As the creator of both the Minwaita and United-gnome AUR package for Arch, it's difficult to use a static file like 'latest' for versioning. Github's releases page would be more helpful. Would this be something you'd be interested in?

**Comment by IamPr377y** [comment]
Use git sha like I do. Theme creator seems to be far away from software development, it's nice of him to even maintain the repo.

**Comment by ainola** [comment]
@IamPr377y But how do you know what revisions are proper? Do you just pick and choose? Go with the latest? This sounds setting up for very poor communication between those reporting issues and the theme creator.

**Comment by godlyranchdressing** [comment]
Thanks. I understand and will look into it. I'm a now starting out web designer (not real development har har) using Git for the first time so I don't really know _exactly_ what I'm doing yet. Sorry for the mess. Expect a release for both United and Minwaita tomorrow.

**Comment by ainola** [comment]
@godlyranchdressing, don't sweat it at all. I think you're doing a fine job. Based on your work I find you more than competent enough for this, even if it's a new experience for you. Feel free to reach out to the community you're building for any questions or concerns!

**Comment by IamPr377y** [comment]
@ainola, I try to build and push to Copr only if build succeeds. Even if we had proper versioning, wouldn't you be building something like `1.2.3git123abc`?

**Comment by godlyranchdressing** [comment]
I think I did it properly.

**Comment by ainola** [comment]
@godlyranchdressing, great! Thanks so much for these great themes!

(By the way, there is no issue tracker set up for Minwaita, so there isn't a place where issues can be reported.)

**Comment by godlyranchdressing** [comment]
@IamPr377y I've made a variant for Fedora in case you want to put that in the repo as opposed to the Ubuntu theme.

**Comment by IamPr377y** [comment]
Updated package to use Fedora variant. I think it's time for you to share _makefile_ with us and remove `*.tar.gz` files from sources.

**Comment by godlyranchdressing** [comment]
I'll look into it. That'll be a first for me.

**Comment by ainola** [comment]
@godlyranchdressing, great work on the distro-specific theming! Are there plans to put these as parts of releases alongside the Ubuntu//Fedora versions?

**Comment by godlyranchdressing** [comment]
@ainola Yep. Was just doing some testing.
