### ISSUE TITLE
Possible consistency issue

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#27]
So there are these little cog style icons for settings that I see in certain places, like at the bottom right of the Search subsection of the control panel (settings app) which have a circular Gray outline and flash to White/Orange on hover. I see the same cog icons in other places like the Extensions section of Gnome Tweak Tool, but without a circular Gray outline. Is it intentional to have these two styles or is it an error?

It may be that you only intend for there to be an outline on a Gray background, that's the only distinction that stands out to me between the two.

**Comment by godlyranchdressing** [comment]
Weird inheritance and tagging issues again. Tweak Tool has those cogs "properly" labeled as button.image-button whereas Settings just has them as "button", probably expecting themes to target them by writing a "toolbar button" rule (which I've done to fix the problem). 

Fixed.
