### ISSUE TITLE
Calculator button colors

### ISSUE THREAD

**Issue by hanjiexi** [godlyranchdressing/United-GNOME#28]
Hello,

The calculator buttons are inconsistent; some are purple and some are gray. I'm on the most recent version of United GNOME.

![calculator_005](https://cloud.githubusercontent.com/assets/5695330/25558823/bd2f4764-2cfc-11e7-8b0c-3e885724e87e.png)

**Comment by godlyranchdressing** [comment]
Woah! Fixed, as well as the titlebar button.
