### ISSUE TITLE
Missing Ubuntu icon

### ISSUE THREAD

**Issue by hanjiexi** [godlyranchdressing/United-GNOME#29]
Hi, the Ubuntu logo is now missing from the launcher button, and I tracked down the lines of code that broke this. Please see my comment here: https://github.com/godlyranchdressing/United-GNOME/commit/f25d1108f3ac1dab121490a8d170907acefc78f0#commitcomment-21962490

**Comment by godlyranchdressing** [comment]
Whoops. I just updated the .css file and didn't include the new assets folder.

**Comment by bill-mavromatis** [comment]
Hey @godlyranchdressing! I'm hearing some complaints regarding the ubuntu-logo.svg missing https://github.com/bill-mavromatis/gnome-layout-manager/issues/11
Would it be possible that you repackage the tar.gz and include it in the assets folder? Thanks!

**Comment by godlyranchdressing** [comment]
It's been fixed. Sorry guys.
