### ISSUE TITLE
Maybe some colors here could be nice?

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#3]
![image](https://cloud.githubusercontent.com/assets/26358664/25283224/b5782348-26bb-11e7-9a55-053b417a8625.png)

As you can see the "Frequent" and "All" selections when applications menu is opened. They have no colors at all so it is hard to notice. I suggest to add the slight orange color and little stronger orange hover color to here.

Thank you in advance. And other than that. This theme is beginning to look quite awesome. 

PS. I also hope you could make another brach which has the main ok button as orange as well. I guess it is not that difficult to change that color.

**Comment by juhaku** [comment]
![image](https://cloud.githubusercontent.com/assets/26358664/25283457/8459b58c-26bc-11e7-97e6-9d5be16b3f9e.png)

One bug in United theme. There is additional grey borders in New window link that most likely should not be there.

**Comment by godlyranchdressing** [comment]
It now looks like the below, with the orange helping visibility in case a dark wallpaper is being used.
![preview](https://cloud.githubusercontent.com/assets/27529229/25287882/23c9220a-2691-11e7-9f3c-1875fb9e8be6.jpg). It'll take a while before I push out these changes though.

Also, thanks! I hope this doesn't sound rude but you're right, it isn't that difficult. I'll release a purple only and orange only version once I'm done cleaning up the gtk3 theme. I'll also make those grey borders look less out of place. They're supposed to be there, they appear on elements that have keyboard focus.

**Comment by juhaku** [comment]
Not at all. Great that looks fantastic. 

Allright, I'll be waiting on them.
