### ISSUE TITLE
Window List extension button styles

### ISSUE THREAD

**Issue by doctorlard** [godlyranchdressing/United-GNOME#30]
I have no idea if it's possible, and I guess it shows up how old-fashioned I might be for using the Window List extension anyway, but it doesn't look like the theme button styles are picked up in the Window List (it still uses shaded rounded button styles). See screenshot (using United Dark) 
![window-list-gnome3-united-dark](https://cloud.githubusercontent.com/assets/316277/25686393/df7a7ad2-30c1-11e7-9fbe-cc0806e596e9.png)

**Comment by godlyranchdressing** [comment]
So I tried getting to it and I'm having a hard time getting rid of what I thought was just an inset box-shadow. It looks like it might be hardcoded and heavy changes aren't possible through CSS. Leaving open in case anyone has any ideas.

**Comment by godlyranchdressing** [comment]
Doesn't seem possible.
