### ISSUE TITLE
Global menu padding

### ISSUE THREAD

**Issue by bill-mavromatis** [godlyranchdressing/United-GNOME#31]
Hi @godlyranchdressing, I'm testing the global menu, but the padding doesn't look too good (also the fonts seem to be bold instead of normal). Do you have any ideas on how to fix this? The issue is referenced here: https://github.com/lestcape/Gnome-Global-AppMenu/issues/24

**Comparison**
United:
![United](http://i.imgur.com/uAtcgzS.png)

Unity:
![Unity](http://3.bp.blogspot.com/-Uvc8eG5uSbQ/T_FUgFvVBCI/AAAAAAAAEMc/E3h4WXyDY0k/s1600/Always+Visible+Global+Menu+in+Ubuntu+Unity.png)

**Comment by bill-mavromatis** [comment]
I think I figured it out... It was not an issue with united shell but it can be fixed in the global menu css like this:

```
* {
    font-family: "Ubuntu Light";
    font-style: normal;
    font-weight: normal;
    font-size: 14px;    
}

.popup-menu-box {
    padding-top: 1em;
    padding-bottom: 1em;
}

.popup-menu-item {
    padding-left: .8em;
    padding-right: .8em;
    vertical-align: middle;
}

.not-ornament {
    /*padding-left: 32px;*/
    icon-size: 1.09em;
}
```

Looks much better now!
![u](http://i.imgur.com/wiX6ODm.png)
Sorry for the hassle! I will close this.

**Comment by godlyranchdressing** [comment]
I guess Lestscape updated something since I remember putting padding for the menu items some time ago. Reopening just so I can remember to double check

**Comment by bill-mavromatis** [comment]
I made a [fork](https://github.com/bill-mavromatis/Gnome-Global-AppMenu) of the Global Menu and added it on my script! I changed the css as above. I'm not 100% what change you made but you somehow fixed the color of the menu text! It used to be yellow/golden and now it's white (as it should).  Good stuff.

**Comment by godlyranchdressing** [comment]
That's good to hear! I'm using Fedora now so getting the extension back up and running might be a task.
