### ISSUE TITLE
Round icon is missing & application icon colors

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#32]
Hey, seemingly round icon is now missing for short dash. See picture
![image](https://cloud.githubusercontent.com/assets/26358664/25779175/e3b52e52-331a-11e7-80b7-276a97eb158e.png)

And propably something could be done for the background of application icon in top left corner. As it becomes a little disturbing in darker when having a white box. I quess it should be more like in dark theme having grey box instead.
![image](https://cloud.githubusercontent.com/assets/26358664/25779190/35f45b84-331b-11e7-9787-5caaac458a26.png)
![image](https://cloud.githubusercontent.com/assets/26358664/25779200/5f80ee40-331b-11e7-9832-817832da17fe.png)

**Comment by godlyranchdressing** [comment]
Fixed the first issue. Really not sure how to go about with the second since the icon just doesn't appear for me when I turn off the appmenu. I'll be moving to Fedora soon so hopefully I don't get the same issue.

**Comment by juhaku** [comment]
The second issue is fixed in V2.0 version branch. :D Which is good. So this can be considered as done.

However there is something fishy in open file dialog if united darker is being used. Example picture from libre office calc.
![image](https://cloud.githubusercontent.com/assets/26358664/25808504/f3a6f536-3412-11e7-8d00-f10b856fe027.png)

**Comment by juhaku** [comment]
Another issue with short dash. When using short dash and hovering over last or first item depending on which side has the application menu. The hover will look as follows. There is no round border even there should be if doc is using round borders.
![image](https://cloud.githubusercontent.com/assets/26358664/25809143/d12752d8-3414-11e7-8374-4394c1456613.png)

**Comment by godlyranchdressing** [comment]
Fixed the dash issue.

**Comment by godlyranchdressing** [comment]
Fixed.
