### ISSUE TITLE
Dialog message not visible anymore

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#33]
Another issue I found out now is that dialogs with checkbox does not show the message anymore.
![image](https://cloud.githubusercontent.com/assets/26358664/25783965/cf98ab08-336d-11e7-9bf1-2c13fabb0f27.png)

**Comment by godlyranchdressing** [comment]
What program is giving you that prompt? It'll be a big help if I could bring it up whenever I wanted since I rarely see it.

**Comment by juhaku** [comment]
It's the alias "Passwords and Keys" application itself should be: Seahorse. When there is SSH keys stored in this app the passphare will be prompted by this application.

Alright I'll take a look at them as well. Thanks for hint.

**Comment by godlyranchdressing** [comment]
Seems to be working fine for me so far. What about you? It could very well be a character limit problem.

**Comment by juhaku** [comment]
That might be, it might be one of gnome 3.24 bugs as well so no need to investigate further. It will be fixed eventually by gnome development team.

**Comment by godlyranchdressing** [comment]
Hopefully. Closed with good faith. Lol.
