### ISSUE TITLE
Add a distro-agnostic menu button

### ISSUE THREAD

**Issue by Ufeldraku** [godlyranchdressing/United-GNOME#38]
^

**Comment by godlyranchdressing** [comment]
Sure. Should be easy enough to do.

**Comment by godlyranchdressing** [comment]
In progress.

**Comment by godlyranchdressing** [comment]
Logo ideas? Default app grid icon or GNOME logo?

**Comment by jsnj** [comment]
Well assuming you'll just be including additional svg(s) in the assets folder, throw them both in. Ideally, you can include a script of some sort to enable the user to choose/change highlight color and logo, similar to the way [numix-folders](https://github.com/numixproject/numix-folders) does it. But that's decidedly more involved and complicated.

**Comment by godlyranchdressing** [comment]
Fixed. For now, the logo can manually be changed. 

As for the script, we'll see how the bash course I'm taking goes.
