### ISSUE TITLE
Padding is too tight on latest release

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#39]
Many items are too squished together now. (padding was perfect before imo) The close buttons in the Activities Overview are also too small >< I much prefer the fatter size to make it easy to access controls on my laptop where I'm using a less precise trackpad over a mouse. If this the new aesthetic direction then feel free to ignore me lol.

Examples:

1) Top right of panel
![Panel Padding](http://u.cubeupload.com/cynicist/panelpadding.png)

2) Right click menu
![Right Click Padding](http://u.cubeupload.com/cynicist/menupadding.png)

3) Video player controls
![Video Player Padding](http://u.cubeupload.com/cynicist/videopadding.png)

4) Buttons on apps
![Button Padding](http://u.cubeupload.com/cynicist/filemanagerpadding.png)

**Comment by godlyranchdressing** [comment]
The big padding was mostly a Flat Plat leftover but I'll try and make it a little more generous.

**Comment by godlyranchdressing** [comment]
Fixed.

**Comment by ElectricGestalt** [comment]
May be a tad too big on the menus now, but better too big than too small. Could you embiggen the back/forward buttons on Nautilus and the spacing between the media player buttons? They're actually even smaller/closer together than before. It's not a huge deal, but I notice myself having to concentrate a bit more to make sure I don't hit the wrong one.

Also, the padding shown below was a bit bigger and nicer before this latest release. (imo, if you disagree then keep the change ofc)

Top is newer, bottom is older
![padding](http://u.cubeupload.com/cynicist/paddingitems.png)
