### ISSUE TITLE
Text size or padding

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#4]
Hi,

One more thing. Don't get me wrong my intention is not to be rude. But I want to help you to finalize the theme. That's why I report these issues.

With dialogs there is an issue that the text for checkbox cannot completely fit to it's place. Also I noticed that in these similar dialogs when for example closing computer or choosing to log out there is no hover on buttons. 

![image](https://cloud.githubusercontent.com/assets/26358664/25294371/81a5673e-26e7-11e7-99d2-7fbb6d322117.png)

Thanks

**Comment by godlyranchdressing** [comment]
I don't mind at all! There's no way I'll be able to discover all these hiccups myself.

**Comment by juhaku** [comment]
Haha, 

I think I found the issue with the hover in dialogs. The reason there is no hover is that they are not focused by the time they are popped up.  That makes annoying glitch that there is a need to actually click twise in order to close the dialogs. The first click will focus the dialog and then second one will close it. After the first click the hovers will also start working. I'm not sure but I guess there is a way that something like this ":focus" can be called in order to get the focus without first click. 

Anyway the second thing I think that text box looks quite suitable to this theme. But when you open the application menu the search box looks quite ugly white box. I think it would also need some orange border. Same goes to login screen's password field.
