### ISSUE TITLE
A feature request

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#40]
Hello,

As I'm a big fan of this theme and seemingly the fedora version looks quite polished and robust. Can you make green version for OpenSuse? 

Also I think it would be really nice the get these themes without the logo as well as an addition for people who would like to use for example the fedora version's blue theme for ubuntu. Of course for ubuntu with fedora logo would not sound too tempting.

**Comment by godlyranchdressing** [comment]
Sure. I'll do a couple variants for the major distros that ship with GNOME and also some agnostic shell themes based on a couple of those (green, orange, etc.). The GTK2 and 3 themes have no branding so mixing and matching should be easy enough.

**Comment by godlyranchdressing** [comment]
Semi-fixed. New variants include Manjaro, Arch, Solus and OpenSUSE. 

The agnostic Shell themes have a couple issues (even though they REALLY shouldn't that I'm having trouble sorting out).

**Comment by juhaku** [comment]
Wow.... that, is, fabulous. Looks so awesome nice job? Do you want me to update the login themes for all of the features? How do you think?

Okay hope you get them solved.

**Comment by godlyranchdressing** [comment]
If you'd like. It'll just be a lot to juggle. If anything, having this many variants forced me to write a script to automate compiling, moving, etc.

**Comment by IamPr377y** [comment]
@godlyranchdressing We need this script! More on this, storing compiled files in git is not a good idea. It would be nice if we could run `make fedora` and get `United{,-Dark,-Darker,-Light}` as output, run `make ubuntu` and get the same output but with different colors, etc.

**Comment by godlyranchdressing** [comment]
The script is more "more fun with for loops" than anything else. Taking arguments and the like is something I've yet to learn. I'll share it once I do some tidying up since it's still better than nothing at this point.

**Comment by juhaku** [comment]
Alright.. I'll be waiting.. Altought if it's something else than shell script it might be new to me as well.. haha
