### ISSUE TITLE
Dialog box default choice colored

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#42]
I'm not sure if this is a design choice or bug but the default option of choice dialogs is now colored as shown below.

![Dialog](http://u.cubeupload.com/cynicist/dialog.png)

**Comment by godlyranchdressing** [comment]
It was a conscious and momentarily second-guessed decision. I'm open to ideas.

**Comment by ElectricGestalt** [comment]
Haha I hope I didn't cause that. I think the reason why I considered it a possible bug is the color choice maybe? It's very strong and bright, which is unusual for this kind of dialog. What about gray instead?

Example 1: 

![Example 1](http://u.cubeupload.com/cynicist/newdialog.png)

Example 2: 

![Example 2](http://u.cubeupload.com/cynicist/newdialog2.png)

**Comment by BooBerry** [comment]
Personally, I like example 3 here.

**Comment by godlyranchdressing** [comment]
Going with example three as it matches the hover effect. It'll match the "pre-action" theme. 

![final](https://cloud.githubusercontent.com/assets/27529229/25965352/3002f282-3634-11e7-8c74-b8d6f005ec59.jpg)

**Comment by ElectricGestalt** [comment]
Just wanted to add, I think it looks really great! The solid color on hover/click is a nice touch imo.
