### ISSUE TITLE
Gtk2.0 close buttons

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#43]
Hello updated the theme for latest tar ball and one thing I found out is that gtk2.0 close buttons are not visible on hover. In the below picture I have mouse over the close button of terminal. And instead it turning to orange it vanishes. without hover it's normal grey.
For gtk3.0 it looks okay.
![image](https://cloud.githubusercontent.com/assets/26358664/25954379/cb5f10a0-366e-11e7-801e-82318387c805.png)

**Comment by juhaku** [comment]
False alarm, there is no issue. sorry. I'll close this one

**Comment by godlyranchdressing** [comment]
Phew. Had me panicking for a while. I've noticed that a couple GTK2 apps don't refresh automatically if the theme is changed and some assets might get messed up until you restart the app. Any GTK3 app that runs in the background can have the same problem, like gnome-terminal-server and nautilus (if you enable desktop icons).
