### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#44]
I updated the login theme's css and it causes the launcher to be dispositioned. See from below pictures.
![image](https://cloud.githubusercontent.com/assets/26358664/25956575/ca642144-3674-11e7-9d28-85d321789ff6.png)

**Comment by juhaku** [comment]
But the new login screen comes quite neat with it as you can see, below is my own background pic in it though but otherwise it has all the animations as well so it's lot cooler than the previous one I made back then.
![image](https://cloud.githubusercontent.com/assets/26358664/25957245/86c0712a-3676-11e7-90f1-046d28f04e80.png)

**Comment by juhaku** [comment]
By adding margin 6 then will fix it like so. 
![image](https://cloud.githubusercontent.com/assets/26358664/25958555/98b0a0c8-3679-11e7-8b6e-db896a4f711b.png)
It will be centered
![image](https://cloud.githubusercontent.com/assets/26358664/25958567/a049c99a-3679-11e7-9369-d1f47c5752de.png)

**Comment by godlyranchdressing** [comment]
Should probably make a README for installing the login theme. Is there a way to get around having to use the margin fix? If not, it'll need to be included in the guide.

**Comment by juhaku** [comment]
Yea I can take a look at that. I could write a proper README with install instructions as well as editing instructions. Also I could write install script for login theme. For pre compiled versions there is no need to worry about padding fix. And also if the fix is added to source already then users has nothing to trouble. But someone wants to build login theme from fresh files then it should be mentioned. I think I can add it to README as well.

**Comment by juhaku** [comment]
Though I think I'll need to redo the login theme from scratch because for a first login screen the new one needs some fixing.

**Comment by godlyranchdressing** [comment]
Alright, great!

**Comment by ElectricGestalt** [comment]
Hey @ juhaku, great job on the theme, it's beautiful! Is it supposed to display your background by default? For some reason mine is a solid color.

**Comment by juhaku** [comment]
@ElectricGestalt good to hear.. Actually no. My own background is only for my use. But I'll make login them with the wallpaper provided by @godlyranchdressing

**Comment by godlyranchdressing** [comment]
There's that noise_texture svg that's meant to work as an overlay over solid colors and stylize it. AFAIK it's how Adwaita gets its grainy look for the lockscreen background. It might be possible to make any solid color look like the Ubuntu wallpaper in the repo with a couple tricks. I'll try something.

**Comment by juhaku** [comment]
Alright, its really weird why the new css will break up somethings in the login. But if old one is used it works alright. Also the old one does not break the dash launcher.

What's your call should the old css being used or should we still look for solutions to fix login for new css?

**Comment by juhaku** [comment]
I think I got a hold on it what need to be fixed on new css. But only thing I dont yet know is how I get the calendar wider as following information cannot fit to content at login. screen
![image](https://cloud.githubusercontent.com/assets/26358664/26015618/6a670fb2-376a-11e7-9c29-ef34c6ad1700.png)

**Comment by juhaku** [comment]
I uploaded new login theme to a new branch. There is installer wizard and README for it as well. It currently looks like this.
![image](https://cloud.githubusercontent.com/assets/26358664/26027018/355c62b8-380f-11e7-8c7e-db38f94b88e3.png)

**Comment by godlyranchdressing** [comment]
#calendarArea {
    min-width: [value here])
} 

Should work if you want to make the calendar wider. Looks nice, the entry field would need to be rounded to follow the new design though (sorry!). 6px is the border-radius value I'm using now. Don't worry about the buttons though, I'm only having OSD (volume control, app switcher, etc.) elements have rounded corners in the Shell theme.

**Comment by juhaku** [comment]
Alright, once you make a first release with rounded up things I'll make changes here as well. :) Yea, I once tried with that and honestly almost every calendar tag there as well but didn't get it it right.. It started to fall apart after it looked okay in login it totally went south on desktop. LOL :D Anyway I'll try that again, maybe I had too small value there before.

**Comment by godlyranchdressing** [comment]
No, I think that's it. I'd mimic the GTK3 buttons normal/hover/active styling for the login dialog buttons. I think I'll try working on the logins themes as well.

I didn't see this message till now.
