### ISSUE TITLE
Gnome launcher

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#45]
How do you like my gnome launcher?
![image](https://cloud.githubusercontent.com/assets/26358664/25965709/78cdc3d6-3691-11e7-9312-bf4f26848d7b.png)
I can give it to you if you want to provide it as default no launcher for no braching styles.

**Comment by godlyranchdressing** [comment]
I like it! This actually gives me an idea. Instead of making an agnostic variant there could just be a folder with launcher buttons if someone wants to replace the branded icon with one. You can push a launcher-icons folder and add it if you'd like.

**Comment by juhaku** [comment]
Great, I'll do that.
