### ISSUE TITLE
Any plans to make this more true to the concept?

### ISSUE THREAD

**Issue by GreyAsteroid** [godlyranchdressing/United-GNOME#46]
I had seen the concept this theme is based on quite some time ago but only today did I come across the omgubuntu article about it becoming a reality. I saw the screenshots and tried it out but it seems this theme has changed quite a bit since then and is becoming just another material design theme. I found some forks of the older theme and I really liked the purple accents, lighter shadows, more button padding and no circles around the window controls so it doesn't look so crowded, etc. etc. 
Getting to the point, are there any plans to make this theme closer the concept or the original version? Even something small like adding a variant with the original purple accent instead of orange?

**Comment by godlyranchdressing** [comment]
I was thinking about that just today, actually, but I'm not sure where to go as yet. Either closer to the concept or closer to Unity 8. It's been a mashup of both with some Material Design subconsciously thrown in. 

I'd hate to alienate people that like the direction the theme is going so far but then I'm sure some people aren't liking where it's going. I usually go with the general consensus so don't be afraid to say something looks like shit or is unoriginal. 

Though people *are* free to fork and go wherever they want with the theme. I think it's in a much more forkable place right now, excluding the quick compile script but I'm working on that. 

A purple version is easy to do. I'll probably put one out tomorrow.

**Comment by GreyAsteroid** [comment]
Good to hear about the purple version, I was actually in the middle of trying to make an ugly love child based on the current version and the colors from an older forked version. 

I didn't see anyone complaining about the direction the theme is going so I figure I'm just a lone party pooper. 

The reason I was looking into the concept and found this theme is because it seems like every single new theme that comes out is just another take on material design and I wanted something new. 

What I particularly liked about the concept and older theme was that they didn't try to do the whole high contrast thing. Elements were different enough that you could tell them apart but through lighter drop shadows and similar colors between elements they seemed to flow together instead of looking like an element is directly on top of another.

Now, I still think this theme is fantastic. Where it's at right now I'd choose it over all the material design themes out there. It's just very different than what it was before and what I'm looking for right now; so again, I'm just a lone party pooper.
