### ISSUE TITLE
breath-gtk-theme colors  for  Manjaro variant.

### ISSUE THREAD

**Issue by ceyhunnabiyev** [godlyranchdressing/United-GNOME#47]
Hi @godlyranchdressing ,
It would be nice to use breath-gtk-theme colors for Manjaro variant, because your theme colors doesn't look cool with  Manjaro gtk icons, especially with Arc-Maia icons. 

Thanks for great theme,
Regards..

**Comment by godlyranchdressing** [comment]
I'll do some experimenting and see how it looks.

**Comment by ceyhunnabiyev** [comment]
Thanks, Great Work!!
