### ISSUE TITLE
Remove theme folders out of top directory

### ISSUE THREAD

**Issue by jsnj** [godlyranchdressing/United-GNOME#48]
Current hierarchy doesn't support the install script on gnome-look.org and creates an unnecessary additional step when extracting. The xz file with the theme folders is all that's needed.

**Comment by bill-mavromatis** [comment]
Hi @godlyranchdressing, I have a similar issue and don't want to open a new one. Can you kindly keep the naming/folder/compression consistency, if possible? I don't really mind the specific hierarchy as long as you keep the same all the way through. The only problem is that if you rename a folder, the URL changes and sometimes the folder paths so my script breaks. Thank you in advance!

**Comment by godlyranchdressing** [comment]
Sorry. Will be fixed on next commit.
