### ISSUE TITLE
Firefox scrollbar

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#49]
Only scrollbar I can still think of needs fixing is the firefox scrollbar. That is still old grey not orange even it should be though.

**Comment by godlyranchdressing** [comment]
I'm honestly not sure where to start with Firefox. It seems to force its own styling and inherit at random but I'll look into it.

**Comment by juhaku** [comment]
Yea.. I can believe that. good luck :) I'm not sure does peeking adwaita help as Adwaita has correct blue scrollbar.

**Comment by ainola** [comment]
Firefox has plans to drop support for heavyweight themes by the end of this year:  I'm not sure how much effort anyone would want to put into this.

**Comment by jhasse** [comment]
> Firefox has plans to drop support for heavyweight themes by the end of this year: I'm not sure how much effort anyone would want to put into this.
