### ISSUE TITLE
Gnome Terminal Preferences

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#5]
The Help and Close buttons do not look like buttons or act like them on hover or click.

**Comment by godlyranchdressing** [comment]
Semi-fixed. Those buttons in GNOME Terminal appear to be "button" as opposed to "button.text-button" where it would inherit the proper styling. In the theme, "button" has no default styling to prevent sub buttons inheriting unintended styles. I had to do a crazy rule to get around it. button:not(.text-button):not(.other-type):not(.another-type) ad infinitum. It fixed the issue but it could lead to other issues. Leaving open for now.
