### ISSUE TITLE
Notebook header tab opinion

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#52]
I thought the previous look was perfect. The new size is too small. Screenshots below. Anyone else want to chime in?

![notebook header broken](http://u.cubeupload.com/cynicist/notebookheaderbroken.png)
![notebook header fixed](http://u.cubeupload.com/cynicist/notebookheaderfixed.png)

**Comment by ElectricGestalt** [comment]
I did learn which setting was responsible for this so no worries if you would rather keep it as is.

I've also been playing around to learn more, and wondered what you would think of 

`window.nautilus-window header tabs tab {
  padding: 0px 6px;
}`

being set to 

`window.nautilus-window header tabs tab {
  padding: 2px 6px;
}`

I think the added room is nice but you may prefer the tighter look.

![Window header 1](http://u.cubeupload.com/cynicist/windowheader1.png)

![Window header 2](http://u.cubeupload.com/cynicist/windowheader2.png)

**Comment by godlyranchdressing** [comment]
I've added some more padding. I just tried it with the Ubuntu font and it really is a bit squashed.

Also, whoops @ semi-colon.

**Comment by godlyranchdressing** [comment]
How is it now?

**Comment by ElectricGestalt** [comment]
Much better! I see that you left the Nautilus tabs the same, but those were the least problematic. It's also nice how you varied it, from Gedit to the properties window sizes. (Assuming that was intentional!!! :smile:)
