### ISSUE TITLE
Squashed player controls and nav buttons

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#55]
I personally think they are way too small, and I wanted to make a suggestion. Set min-width: 25; (or somewhere around that value) for button.image-button:not(.text-button). It solves the issue entirely. The buttons on the right hand side have some additional padding or something that I am having trouble finding, but even then they are not spaced too far apart.

Before:
![Before min width](http://u.cubeupload.com/cynicist/beforeminwidth.png)

After:
![After min width](http://u.cubeupload.com/cynicist/afterminwidth.png)

What do you think?

**Comment by godlyranchdressing** [comment]
I've added some padding and adjusted the min-width and height to make them all (image-button:not(.text-button)) 32x32px.
