### ISSUE TITLE
google chrome suggestion

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#56]
i think it will be better if u made the bar behind the Tabs is black too like firefox in Darker theme

**Comment by godlyranchdressing** [comment]
Oh right. I forgot I could do that. It'll be changed in the next commit.

**Comment by amrsaraya** [comment]
@godlyranchdressing i think you forgot to add this to the latest release of "concept" branch.

![screenshot from 2017-05-17 14-58-14](https://cloud.githubusercontent.com/assets/21042432/26154826/ac109322-3b19-11e7-8b00-14806aa8e151.png)

**Comment by godlyranchdressing** [comment]
I haven't forgotten. The only thing that hasn't been changed/updated in the concept branch is the GTK2 theme.

**Comment by amrsaraya** [comment]
Oh, i didn't know sorry.

**Comment by godlyranchdressing** [comment]
It's alright. I should probably include a readme in the non-master branches explaining what's going on in them.
