### ISSUE TITLE
Login themes

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#59]
Hey @godlyranchdressing,

Could you provide me the wallpapers for different variants so I can make rest of login themes?
I'll already got a wallpaper for OpenSUSE

**Comment by godlyranchdressing** [comment]
Uploaded [here](https://github.com/godlyranchdressing/United-GNOME/blob/master/distro-previews/Wallpapers.tar.xz). These came with Fedora IIRC, one of them from 24.

**Comment by juhaku** [comment]
Thanks, I'll get back with new versions anytime soon

**Comment by juhaku** [comment]
Fedora login theme:
![image](https://cloud.githubusercontent.com/assets/26358664/26287057/ba7bd042-3e7b-11e7-9582-def0d7c5d719.png)

**Comment by juhaku** [comment]
Ubuntu login theme:
![image](https://cloud.githubusercontent.com/assets/26358664/26287067/129a666c-3e7c-11e7-9a98-afb885bcb0fd.png)

**Comment by juhaku** [comment]
I also added theme for opensuse but the theme will break the boot. I dont know why but there is something strange in the theme files. So it cannot be used before issues are solved.

**Comment by juhaku** [comment]
Please merge them if you see they are alright and please test them out and see if there is something that should be changed.

**Comment by godlyranchdressing** [comment]
The Fedora theme looks fantastic, it's too bad I can't take screenshots when the screen is locked, haha. I did notice that the calendar arrow disappears when you put your mouse over it and when you click it. I'm guessing the solution to that is including:

<file>assets/calendar-arrow-left-hover.svg</file>
<file>assets/calendar-arrow-left-active.svg</file>
<file>assets/calendar-arrow-right-hover.svg</file>
<file>assets/calendar-arrow-right-active.svg</file>

in the XML file. I think I might have an idea of how this all works so I'll make some changes on my end since tomorrow is "Work on GNOME Shell" day.

**Comment by hanjiexi** [comment]
Here is the result of my trying to run the installer script for the login theme:
```bash
$ ./united-login-theme-installer.sh -i
Installing...
What variant you would like to use?
ubuntu
variant ubuntu
Installing ubuntu login theme...
Asking sudo rights to move original theme as back up.
mv /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.bak
[sudo] password for hanjiexi: 
Checking does ubuntu folder exist in current directory.
Find compile command
Compile command found: /usr/bin/glib-compile-resources...
Compiling gnome-shell-theme.gresource.xml...
gnome-shell-theme.gresource.xml: File /org/gnome/shell/theme/assets/calendar-arrow-left-hover.svg appears multiple times in the resource.
Copying compiled gnome shell theme to /usr/share/gnome-shell
cp: cannot stat 'gnome-shell-theme.gresource': No such file or directory
Completed!
Do you wish to reboot now, changes take affect after reboot? (y/N)
N
Press alt + F2 and then type r to restart gnome shell. This makes login theme party available.
```
To double check I also ran this:
```bash
$ ls /usr/share/gnome-shell
extensions                       modes                search-providers
gnome-shell-theme.gresource.bak  perf-background.xml  theme
```
As you can see, it didn't work. It fails to compile the new gresource file, yet the installer script still thinks it was successful.

**Comment by juhaku** [comment]
@hanjiexi Thanks for your feedback.. I'll fix it at once.. However in wich folder did you run it.. As for me it works.. or worked before.. there might me some changes in assets seemingly.. I'll make it bullet proof..

**Comment by hanjiexi** [comment]
I ran it in the login-gnome-shell folder, the same one where the script was located.

**Comment by juhaku** [comment]
Okay.. Then it should work, Yes there was duplicate assets defined in config otherwise it should work. Now it will fail if there is an error and wont continue like nothing was happened. Now this script also should work from other locations as well to add a cherry on top of the cake. So there is no need to run it in the containing folder necessarily. So updated ones are found behind the extras folder.

**Comment by juhaku** [comment]
For those looking to change login theme. There is a new applicaiton I've just launched. https://github.com/juhaku/loginized
If any interests raises check it out
