### ISSUE TITLE
OpenSUSE variant darker

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#60]
In openSUSE variant darker version has issue with assets. See below. All the checkboxes, sliders, radio buttons are missing.
![image](https://cloud.githubusercontent.com/assets/26358664/26032098/4f060640-3893-11e7-87e4-c3e9b07192d7.png)
It should look like this:
![image](https://cloud.githubusercontent.com/assets/26358664/26032113/8a74476e-3893-11e7-9286-6bf7dbb3e452.png)

**Comment by godlyranchdressing** [comment]
Slip up on my end. I'll push out a new version tomorrow so until then people will just have to copy and paste the regular (non-dark) assets folder into the darker gtk-3.0 folder. Sorry
