### ISSUE TITLE
Darker theme maximized issue

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#61]
there is a white line between header bar and menu bar in fedora darker theme when maximized
and that line doesn't exist in dark theme.
(Notice) : This line exists in darker and normal themes only, and doesn't exist in dark theme

![screenshot from 2017-05-14 14-14-45](https://cloud.githubusercontent.com/assets/21042432/26033644/4874f8fc-38b8-11e7-8d0f-0e4c071b37f0.png)

**Comment by ElectricGestalt** [comment]
This issue doesn't exist for me. Could an extension be causing it?

**Comment by amrsaraya** [comment]
@ElectricGestalt even when i disabled all extensions the issue still there.

**Comment by godlyranchdressing** [comment]
Have you tried one of the archives in the repo or are you using the GNOME-Look release?

**Comment by amrsaraya** [comment]
@godlyranchdressing GNOME-Look release works fine ..... the problem exists in repo latest commit

![screenshot from 2017-05-16 15-46-37](https://cloud.githubusercontent.com/assets/21042432/26109164/4c32fbec-3a57-11e7-9e19-a00fed8cfb4b.png)

**Comment by amrsaraya** [comment]
Fixed in last release in the "concept" branch
