### ISSUE TITLE
Theme is very raw for Ubuntu 17.04 - borders, colors, paddings etc.

### ISSUE THREAD

**Issue by kirylpl** [godlyranchdressing/United-GNOME#62]
![screenshot from 2017-05-15 02-24-52](https://cloud.githubusercontent.com/assets/3589618/26038664/0ee1bcc0-3916-11e7-8ba9-2c3ae78f4a42.png)

Hi devs. Let me inform you about what I noticed on my Ubuntu 17.04 (libgtk-3-0:amd64 3.22.11-0ubuntu3 )

1) Filenames unreadable
2) Close Minimize buttons out of general layout paddings
3) Strange borders and paddings
4) Incorrect background color

**Comment by godlyranchdressing** [comment]
I don't use Unity and it's _not being actively supported_ but I'll see what I can do.

**Comment by kirylpl** [comment]
@godlyranchdressing Well, it will be good, for sure. Thank you.
