### ISSUE TITLE
Dialog size

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#63]
Hello I wonder if the dialog is little too small as the text does not fit to it. See below the "privat..."
![image](https://cloud.githubusercontent.com/assets/26358664/26074876/1224654e-39bc-11e7-97cc-d9738bbd851b.png)
It would be really nice if you could extend the width of the dialogs so that the text would fit.

**Comment by godlyranchdressing** [comment]
I could have sworn I _did_. It's been adjusted. Instead of a fixed size it should start at the default of 500 (like in that screenshot) and go up to 600.

**Comment by juhaku** [comment]
Yea. that's strange though..

**Comment by godlyranchdressing** [comment]
You can try out the release in the "concept" branch if you'd like. The fix is in that version.
