### ISSUE TITLE
Text beside icons

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#64]
I think text is too far from icons in toolbar.

![screenshot from 2017-05-17 01-30-20](https://cloud.githubusercontent.com/assets/21042432/26132468/23fdc812-3aa9-11e7-98d3-8e26d66bc1d0.png)

**Comment by godlyranchdressing** [comment]
Will fix. That seems to have slipped in there somehow without me realizing it.

**Comment by amrsaraya** [comment]
appreciate your working.

**Comment by godlyranchdressing** [comment]
Fixed in concept branch which will be merged into master soon.
