### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#65]
i think if u removed this separator it will look awesome like older releases.

![sc](https://cloud.githubusercontent.com/assets/21042432/26136595/b16f5ed8-3ac5-11e7-9346-6fe8851c0245.png)

**Comment by godlyranchdressing** [comment]
That shouldn't be so thick. I'll correct it. Also, thanks for trying out the stuff in the new branch!

**Comment by amrsaraya** [comment]
Np buddy. I enjoy spending time testing your theme, because i believe that it's the most beautiful theme i have ever tried. And you are real artist, Good Job!

**Comment by godlyranchdressing** [comment]
Thanks! Though to be fair I don't deserve all the credit. It's not 100% original. Closing since I just pushed a fixed version to the concept branch.

**Comment by amrsaraya** [comment]
i am going to give it a try right now. thanks alot!
