### ISSUE TITLE
Big Padding under Wayland-Gnome

### ISSUE THREAD

**Issue by VandaLHJ** [godlyranchdressing/United-GNOME#68]
When running gnome terminal under Wayland, padding is extremely big.
When running gnome under Xorg, padding is normal.
Ubuntu GNOME 17.10
Slightly modified United-Gnome-Dark (size of top bar decreased and changed to em to scale better with text).
![zrzut ekranu z 2017-05-18 22-00-00](https://cloud.githubusercontent.com/assets/28790923/26221051/6d8b2d36-3c15-11e7-9df1-3a81448ac9d8.png)
![zrzut ekranu z 2017-05-18 22-01-09](https://cloud.githubusercontent.com/assets/28790923/26221080/8b50cace-3c15-11e7-8b88-d47bb8890b9e.png)

**Comment by ElectricGestalt** [comment]
I'm not seeing that myself. Nothing like those screenshots.

**Comment by godlyranchdressing** [comment]
That's really _weird_. I've tried applying every theme option in the terminal under Wayland in UG 17.04 as well as Fedora 25. I only just noticed you said 17.10 though, do other themes have a similar problem?

**Comment by VandaLHJ** [comment]
Behavior of that padding suggest that it's rather shadow, as you can click on those and for example adjust background. Here is my output of inxi -F:
`inxi -F
System:    Host: XXXX Kernel: 4.10.0-20-generic x86_64 (64 bit)
           Desktop: Gnome 3.24.2
           Distro: Ubuntu Artful Aardvark (development branch)
Machine:   Device: laptop System: LENOVO product: VIWGQ v: INVALID
           Mobo: LENOVO model: INVALID v: 00000000Not Defined
           UEFI: LENOVO v: 79CN50WW(V3.09) date: 10/20/2014
Battery    BAT1: charge: 40.8 Wh 100.0% condition: 40.8/40.4 Wh (101%)
CPU:       Dual core Intel Core i5-4200M (-HT-MCP-) cache: 3072 KB 
           clock speeds: max: 3100 MHz 1: 799 MHz 2: 800 MHz 3: 804 MHz
           4: 800 MHz
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           Card-2: Advanced Micro Devices [AMD/ATI] Jet PRO [Radeon R5 M230]
           Display Server: X.Org 1.19.3 driver: N/A
           Resolution: 1366x768@59.80hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile
           GLX Version: 3.0 Mesa 17.1.0
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller
           driver: snd_hda_intel
           Card-2 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
           driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.10.0-20-generic
Network:   Card-1: Broadcom Limited BCM43142 802.11b/g/n driver: wl
           IF: wlp8s0 state: up mac: XXXXXXXXXXXXX
           Card-2: Qualcomm Atheros AR8162 Fast Ethernet driver: alx
           IF: enp9s0 state: down mac: XXXXXXXXX
Drives:    HDD Total Size: 120.0GB (26.5% used)
           ID-1: /dev/sda model: ADATA_SP550 size: 120.0GB
Partition: ID-1: / size: 110G used: 30G (29%) fs: ext4 dev: /dev/sda2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 44.0C mobo: N/A gpu: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 257 Uptime: 0 min Memory: 1347.6/3861.4MB
           Client: Shell (bash) inxi: 2.3.8 

It's Lenovo g510 laptop with warranty-replaced mobo. 
Those shadows also exist before GDM start. If you want some additional info, just let me know.
`

**Comment by godlyranchdressing** [comment]
Looks like it's an Ubuntu patch causing it. I wonder what it was. Interesting issue, but I'm closing this since it's not my fault, thankfully.
