### ISSUE TITLE
GNOME-software Tabs style

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#69]
GNOME-software tabs style is different from other GNOME apps 

![screenshot from 2017-05-20 03-23-54](https://cloud.githubusercontent.com/assets/21042432/26271906/ee0346a6-3d14-11e7-9590-bfc5752da264.png)

**Comment by godlyranchdressing** [comment]
Forgot to switch that over to the new button mixin. Fixed, but I want to sort out the asset issue before the next commit. Sorry.

**Comment by godlyranchdressing** [comment]
Fixed.
