### ISSUE TITLE
Topicon icons too close to each other

### ISSUE THREAD

**Issue by yejingchen** [godlyranchdressing/United-GNOME#72]
I am using the [Topicon](https://extensions.gnome.org/extension/495/topicons/) extension (not Topicon Plus), but the icons are too close to each other (or the icons are too big?) under this theme:

*(Icons on the left are Topicons)*
![united-ubuntu-light](https://cloud.githubusercontent.com/assets/5119728/26281239/13b6a810-3e24-11e7-9a3c-7dd584055690.png)
(Screenshot under United Ubuntu Light, but all variants behaves the same)

This is what it looks like under default theme and Arc theme:

![2017-05-21 12-46-05](https://cloud.githubusercontent.com/assets/5119728/26281261/842c577a-3e24-11e7-82e1-bf380ef3612f.png)
![2017-05-21 12-47-52](https://cloud.githubusercontent.com/assets/5119728/26281263/87d43816-3e24-11e7-9243-432c92078aea.png)

Please fix this, thanks.

**Comment by godlyranchdressing** [comment]
It looks like the changes I made to get the indicators to look uniform are affecting that extension. I'll see what I can do. Topicon Plus works fine and I don't want to get rid of the indicator spacing so if I have no luck, I'll end up leaving it as is.

**Comment by yejingchen** [comment]
It is strange that when I am testing the concept branch the icon size is normal.
![2017-05-22 14-36-12](https://cloud.githubusercontent.com/assets/5119728/26295495/bf7b87fa-3efc-11e7-9a08-c2073301c463.png)

Maybe modifications in the concept branch has already fixed this.

**Comment by godlyranchdressing** [comment]
No luck, but I'll keep trying again.

**Comment by godlyranchdressing** [comment]
Doesn't seem fixable without altering the indicator spacing. Closing since there's TopIcon Plus which works fine. Sorry!
