### ISSUE TITLE
Input method color makes selected candidate hard to read under light shell theme

### ISSUE THREAD

**Issue by yejingchen** [godlyranchdressing/United-GNOME#73]
When using a input method, a user type several key sequence and select one from some candidates. The "Selected" one is highlighted using foreground color in GNOME shell, but in United Ubuntu Light the color of selected text doesn't change which makes the text hard to read:

![2](https://cloud.githubusercontent.com/assets/5119728/26281569/8b6fc37e-3e2d-11e7-8523-28dc82c29ce0.png)
*(United Ubuntu Light theme; text reads "hello")*

Normal and dark version of united shell themes don't have this issue because texts are all white and readable.

As a reference this is the GNOME Classic theme (which is also a light theme) where the selected text is white:
![default](https://cloud.githubusercontent.com/assets/5119728/26281577/c12b547e-3e2d-11e7-96d3-a728ccb8523f.png)

I've created two mockups, one follows the original design which just make the text white, and the other use the design from the alt-tab app switcher (the same as the input method switcher):
![2-mod](https://cloud.githubusercontent.com/assets/5119728/26281646/58aaf71c-3e30-11e7-921a-6b85d7280241.png)
![2-mod2](https://cloud.githubusercontent.com/assets/5119728/26281647/58b04b90-3e30-11e7-9a82-95e772efea6d.png)

I am not sure whether these mockups are possible, but solving this problem will no doubt be a plus for Asian CJK users who want this theme :)

**Comment by godlyranchdressing** [comment]
I'll work on it. Have you tried one of the releases from the [concept](https://github.com/godlyranchdressing/United-GNOME/tree/concept) branch? They're not really final, but I did make a couple changes that might have fixed your issue. 

I'm actually still trying to figure out how to use the input method switcher.

**Comment by yejingchen** [comment]
I just tried the concept branch and the input method color is the same as master. 

About the way to use the input method swicher:
You need to enable **at least two** input language in the GNOME settings app (in the Region & Language -> Inpur Sources section, click the plus ('+') icon and select one language, any will do), and the default IM switch key is Super + space. If there is no effect, you may check the "Typing" keyboard shortcut settings in settings app.

**Comment by godlyranchdressing** [comment]
谢谢! I'll no doubt push a fix tonight. The light Shell theme has been a bit ignored compared to the other versions. Sorry about that.

**Comment by godlyranchdressing** [comment]
Fixed. Based on your second mockup with a border around the window to help distinguish it.
![b](https://cloud.githubusercontent.com/assets/27529229/26335603/8973e1d0-3f19-11e7-8ef5-2748be273a02.jpg)
