### ISSUE TITLE
Firefox downloads

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#74]
Firefox downloads seems to have too large components.
![image](https://cloud.githubusercontent.com/assets/26358664/26286775/bfa3668a-3e75-11e7-8d65-3640ff7a5d17.png)

**Comment by amrsaraya** [comment]
It works fine in united-fedora.

**Comment by juhaku** [comment]
Strange.. probably my hDPI screen causes some strange issues.

**Comment by godlyranchdressing** [comment]
Might be that. I can't think of anything that might cause that problem.
