### ISSUE TITLE
United-Dark shell

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#75]
Shell background color was #111111, and now it's #252525 .
so it's not dark anymore i think the old one "#111111" is better and fit with dark and darker themes

**Comment by godlyranchdressing** [comment]
You're right. I made it #181818 to match Unity 8.
![a](https://cloud.githubusercontent.com/assets/27529229/26335453/8c83acf8-3f18-11e7-8014-3d037bcd71b7.jpg)
