### ISSUE TITLE
Panel Transparency

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#78]
The new transparency is a bit much imo. It makes it hard to distinguish running apps from the background, unless your background color is significantly different than the orange highlight of the panel. (the new window indicators are nice btw) The old transparency would probably be best, or you could experiment with brighter/darker highlights. There is just not enough contrast right now.

Example:

![Example 1](http://i.imgur.com/zzIDBqc.png)

Contrasting Background:

![Example 2](http://i.imgur.com/CcQXImh.png)

Old Look:

![Old look](http://i.imgur.com/2koEty0.png)

**Comment by godlyranchdressing** [comment]
Right. I always forget to test stuff under different wallpapers. I'll make adjustments.

**Comment by godlyranchdressing** [comment]
**Wow**. Looks like I completely missed that since I unknowingly had Dash to Dock's custom opacity setting on. It's back to the original value and the top panel's transparency has been reduced to match the dash's.
