### ISSUE TITLE
Mismatch on tooltips

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#79]
I love the new, darker tooltips. Unfortunately, the Firefox tooltips did not change. (hover over a tab to see the difference) Is this a typical Firefox issue or just something you forgot to change? Also, the gtk2 tooltips are inverted and appear as Black text on a White background instead of White text on a Black background.

**Comment by godlyranchdressing** [comment]
I did some experimenting and it looks like Firefox overrides any alpha value for tooltips unless that value means no transparency. I'm guessing to avoid readability issues. The tooltips are dark enough that you can barely tell there's transparency applied so I'll just make them solid to get around this.

The GTK2 tooltip inconsistency is on me though.
