### ISSUE TITLE
Close button unreadable (Rhythmbox)

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#8]
I see this bug in Rhythmbox in the Preferences dialog, affecting every tab except the Podcasts one. Interestingly, if you click and hold the close button on that tab and then move your mouse cursor away from it, it also disappears.

**Comment by godlyranchdressing** [comment]
White text? I've seen it before too. Either I can't reproduce it or I fixed it at some point. Will leave open until you can try the latest release tonight and can confirm.

**Comment by ElectricGestalt** [comment]
Yeah, White text. I'll test it for sure.

**Comment by ElectricGestalt** [comment]
This issue is now fixed. :D
