### ISSUE TITLE
Context menu rounded

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#80]
New shell rounded corners looks awesome, i think context menu deserve a shot.

**Comment by godlyranchdressing** [comment]
For the Shell theme or GTK3? 

I'll see how it looks. The first and last times highlighted would have their orange backgrounds rounded so it might look a little weird the way I'm imagining it. Hopefully there won't be any GTK2 issues with it as well.

**Comment by amrsaraya** [comment]
I mean for shell theme.
GTK3 context menu looks awesome already thanks to you.
