### ISSUE TITLE
Dialog checkbox text again not visible, currently on fedora variation

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#84]
Hello, dialog checkbox not visible. I guess it was visible with the ubuntu flavor but for fedora variation it cannot be seen.
![image](https://cloud.githubusercontent.com/assets/26358664/26370185/c4817c4c-3fff-11e7-918c-0855d95ce64e.png)

**Comment by godlyranchdressing** [comment]
What program is giving you the prompt?

**Comment by juhaku** [comment]
It was the seashore passwords application.. but I guess it is not problem of theme..

**Comment by godlyranchdressing** [comment]
Yep. I think it might be either a bug.

![mm](https://cloud.githubusercontent.com/assets/27529229/26470751/43fe0bb0-414b-11e7-934e-f91ce4d22483.png)

Works fine on Fedora 24.
