### ISSUE TITLE
openSUSE variation bug/error

### ISSUE THREAD

**Issue by DenysMb11** [godlyranchdressing/United-GNOME#85]
(Before anything, sorry my bad english)
The default openSUSE variation and the Dark variation are ok:
![image](https://cloud.githubusercontent.com/assets/24397859/26378796/7b9b50ec-3fec-11e7-850c-ffa2fd879f71.png)
![image](https://cloud.githubusercontent.com/assets/24397859/26378815/9165a06c-3fec-11e7-89a2-cf82ff245815.png)

The problem is with the Darker variation. As you can see, the buttons in "Tema global escuro" and "Habilitar animações" doesn't appears.
![image](https://cloud.githubusercontent.com/assets/24397859/26379014/6f2cb0c0-3fed-11e7-972a-39713c6571e4.png)

Here are another error, the default and dark variations are ok:
![image](https://cloud.githubusercontent.com/assets/24397859/26379133/fe62fb28-3fed-11e7-9ccd-89a5f41331ca.png)
![image](https://cloud.githubusercontent.com/assets/24397859/26379165/2147de2e-3fee-11e7-90c0-3c303d04b4b7.png)

But in the Darker Variation, the "circle" doesn't appears:
![image](https://cloud.githubusercontent.com/assets/24397859/26379239/7791a80a-3fee-11e7-80cf-a945539e681d.png)

These are just some bugs that i've found.
By the way, is this the GTK2 of this theme?
![image](https://cloud.githubusercontent.com/assets/24397859/26379403/7fe876f4-3fef-11e7-9313-22054fd57e61.png)

All the "Ubuntu" variations are ok.

**Comment by ElectricGestalt** [comment]
> By the way, is this the GTK2 of this theme?

No. Try launching Gimp and see if it takes effect there. It works fine on my Ubuntu 17.04 installation.

**Comment by DenysMb11** [comment]
I see, it's okay with Gimp.

**Comment by ElectricGestalt** [comment]
It looks like YaST2 inherits from Qt. Try following the advice [here](https://www.reddit.com/r/openSUSE/comments/4jrghn/yast_and_theming/) (the package removal and override) and see if it helps.

**Comment by DenysMb11** [comment]
The YaST problem was solved moving the theme from ~/.themes to /usr/share/themes.
Now just waiting to the problem with the openSUSE Darker variation be solved.

**Comment by godlyranchdressing** [comment]
Are you using the the GNOME-Look version?

**Comment by DenysMb11** [comment]
At the start yes, but then I've downloaded the tar.gz file from here and still the same.

**Comment by godlyranchdressing** [comment]
I just updated the release and double-checked the openSUSE variant. It's working now. The older release had some missing assets. Sorry about that.

**Comment by DenysMb11** [comment]
It's working now. Thank you to solve this!
