### ISSUE TITLE
bottom corners arrows

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#87]
I think these arrows in the bottom corners doesn't loo k good. and i think also user doesn't need it to know this window is resizable, he always try to resize it if he needs even without arrows :D

![screenshot from 2017-05-24 01-19-17](https://cloud.githubusercontent.com/assets/21042432/26380559/ecf8f24a-4027-11e7-8bfe-2cd623bcd565.png)

**Comment by godlyranchdressing** [comment]
Accident. Will fix.
