### ISSUE TITLE
Percentage bar color

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#88]
this bar's color isn't correct, because i don't remember last release' color

![screenshot from 2017-05-24 05-09-18](https://cloud.githubusercontent.com/assets/21042432/26385358/b90b68d0-4047-11e7-81c4-16904d9130af.png)

**Comment by godlyranchdressing** [comment]
Oh, that's on purpose. If the bar is selected then it  becomes white to avoid any clashing colors or readability issues. The progress bar and the background seem to be pretty close in shade though, so I'll make some adjustments.

**Comment by amrsaraya** [comment]
Aha, got it buddy.
appreciate your wok.
