### ISSUE TITLE
Dark themes' problems

### ISSUE THREAD

**Issue by wangxa** [godlyranchdressing/United-GNOME#89]
In Version 2.1, the following themes have two problems:
   `United-Arch-Dark`, `United-Opensuse-Dark`, `United-Manjao-Dark`, `United-Ubuntu-Dark`, `United-Solus-Dark`, and `United-Ubuntu-alt-Dark`

1.  In their `gtk-3.0/gtk-dark.css`, `disabled_bg_color` is not defined.
2.  In their `gtk-3.0/gtk-dark.css`, `-gtk-icon-filter` is not supported until GTK version is equal to or greater than 3.89. So you have to change `-gtk-icon-filter: brightness(1.2);` to `-gtk-icon-effect: highlight;`.

**Comment by godlyranchdressing** [comment]
Are you sure it's 2.1? Because I'm not getting these errors thrown out from the command line or seeing these lines in the CSS files. Can you tell me the line that they're on? 

I actually specifically remember commenting out the -gtk-icon-filter lines since I noticed that error some time ago.

**Comment by ceyhunnabiyev** [comment]
@wangxa, Disable  global-dark-theme option from gnome-tweak-tool.

**Comment by wangxa** [comment]
Thank you, ceyhunnabiyev. You are right. I forgot to disable the global dark theme option.

**Comment by godlyranchdressing** [comment]
Sorry, but I'm still not getting these errors, even with the global dark theme switched on.

**Comment by wangxa** [comment]
I have tried. If the version is the latest git commit, there is no such warnings, even with the enabled global dark theme.

**Comment by godlyranchdressing** [comment]
Alright, great! I remember someone opened a similar issue which I remember fixing so I wasn't sure if I was missing something.

**Comment by ceyhunnabiyev** [comment]
@godlyranchdressing, please look at the difference of pictures, especially color and window control buttons:
![screenshot from 2017-05-26 17-35-41](https://cloud.githubusercontent.com/assets/5506156/26497001/cb412a04-423a-11e7-918e-6903e42ff973.png)

![screenshot from 2017-05-26 17-38-01](https://cloud.githubusercontent.com/assets/5506156/26496973/b633d1e8-423a-11e7-95bc-6c384e04f2cf.png)
