### ISSUE TITLE
File Picker Dialog

### ISSUE THREAD

**Issue by ElectricGestalt** [godlyranchdressing/United-GNOME#9]
Three bugs here.

1. The current directory in the breadcrumbs area should be indicated somehow. (In Adwaita it appears depressed)

2.  Hovering over the left arrow in the breadcrumbs area should cause it to be highlighted orange but doesn't.

3. Hovering over the Create New Folder option should cause it to be highlighted orange as well.

**Comment by godlyranchdressing** [comment]
Fixed. Looks almost identical to Nautilus' pathbar.
