### ISSUE TITLE
Application selector in applications menu is quite light

### ISSUE THREAD

**Issue by juhaku** [godlyranchdressing/United-GNOME#90]
Currently selected icon selector is little too light.. In the picture the first one is the one is highlighted but it can be barely seen.

![image](https://cloud.githubusercontent.com/assets/26358664/26469280/13e9e2ee-41a2-11e7-95d7-6d258eef18dd.png)

**Comment by godlyranchdressing** [comment]
Is that the current version? There should be a border around that as well as a darker color. That's the app grid view, right?
![mm](https://cloud.githubusercontent.com/assets/27529229/26470896/dcc29974-414b-11e7-80cd-c3cbb2e8bc10.png)

**Comment by juhaku** [comment]
Oh.. That is not most recent one though.. but good to know. yea that's the one..

**Comment by godlyranchdressing** [comment]
Is that better? Or should I make it more noticeable?
