### ISSUE TITLE
No brand version

### ISSUE THREAD

**Issue by vortex09** [godlyranchdressing/United-GNOME#92]
Hi, do you plan to develop also a no-brand version?Anyway is there a possibility to remove distribution logo?Thanks

**Comment by godlyranchdressing** [comment]
There's a launcher-icons folder in extras as well as an archive on GNOME-Look. Those icons can be appropriately renamed and used to replace the distro icons. I know it's lazy, sorry, but I don't really want to juggle around 21 more different Shell themes and then another set when the compact variant is done.

**Comment by vortex09** [comment]
Good to hear that!Thanks
