### ISSUE TITLE
New Shell buttons color

### ISSUE THREAD

**Issue by amrsaraya** [godlyranchdressing/United-GNOME#93]
I think the new light grey color isn't that good, i prefer the old one, same as background color.
i think the old one was perfect, why did u change it ?
This one was awesome !
![screenshot from 2017-05-26 16-06-42](https://cloud.githubusercontent.com/assets/21042432/26498516/00c44bfa-4238-11e7-81a3-3f410101fe29.png)

This new one not that good.
![screenshot from 2017-05-26 16-06-56](https://cloud.githubusercontent.com/assets/21042432/26498431/b6d03928-4237-11e7-8abb-de99b72122d3.png)

i suggest to bring back the old one.

**Comment by godlyranchdressing** [comment]
Something something about coherency. They do match the button colors in the dark GTK3 theme, but you're right. They'll be tweaked or just plain reverted in the next release.

**Comment by amrsaraya** [comment]
Thx for fixing.
