### ISSUE TITLE
Radiobuttons, checkboxes, toggles, buttons,... differ from default color

### ISSUE THREAD

**Issue by ceyhunnabiyev** [godlyranchdressing/United-GNOME#95]
Can you plan change  color of asset items to default color (breathe/maia)?

![screenshot from 2017-05-26 19-57-31](https://cloud.githubusercontent.com/assets/5506156/26502462/f34aba02-424d-11e7-914e-9ec006fa2aee.png)

Great theme,
Regards.

**Comment by godlyranchdressing** [comment]
No, sorry. They're a different color for a reason and the Ubuntu variant gets first priority. Picking up a variant and giving it specific styling is something I'll leave for a fork.
