### ISSUE TITLE
Top bar and header bar fixed size

### ISSUE THREAD

**Issue by VandaLHJ** [godlyranchdressing/United-GNOME#98]
Due to pixels usage in css style in both top and header bars, they look not uniform at different desktop resolutions. Easy fix is using em instead of pixels to make the look consistent between different resolutions, and it's also making it better at handling hi-dpi and 4k.

**Comment by godlyranchdressing** [comment]
Will do. Someone said the Shell theme's text was too small as well so I figured it might be that.
